//! `INDEX.md`: a generated chronological table of runs.

use std::fs;
use std::path::Path;

use crate::model::parse_manifest;

/// One row of the index.
#[derive(Debug, Clone, PartialEq)]
pub struct RunRow {
    pub run_id: String,
    pub sha: String,
    pub timestamp: String,
    pub headline: String,
}

/// Extract the `## What changed` headline (first non-blank line of that
/// section) from an `entry.md` body. Empty string if absent.
pub fn extract_headline(entry_md: &str) -> String {
    let mut in_section = false;
    for raw in entry_md.lines() {
        let line = raw.trim();
        if let Some(rest) = line.strip_prefix("## ") {
            // entering / leaving a section
            in_section = rest.trim() == "What changed";
            continue;
        }
        if in_section && !line.is_empty() {
            // stop at a placeholder author prompt like "<one-paragraph ...>"
            if line.starts_with('<') && line.ends_with('>') {
                return String::new();
            }
            return line.to_string();
        }
    }
    String::new()
}

/// Render the INDEX.md markdown from rows already ordered newest-first.
pub fn render(rows: &[RunRow]) -> String {
    let mut out = String::new();
    out.push_str("# Journal index\n\n");
    out.push_str(
        "Chronological table of recorded runs (newest first). Generated by `journal index`.\n\n",
    );
    out.push_str("| run-id | sha | timestamp | what changed |\n");
    out.push_str("|--------|-----|-----------|--------------|\n");
    if rows.is_empty() {
        out.push_str("| _(none)_ | | | |\n");
    }
    for r in rows {
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            r.run_id,
            r.sha,
            r.timestamp,
            r.headline.replace('|', "\\|")
        ));
    }
    out
}

/// Scan `<journal>/runs/*` and build the index rows, newest first (by run-id,
/// which is timestamp-prefixed so lexicographic order is chronological).
pub fn collect_rows(runs_dir: &Path) -> std::io::Result<Vec<RunRow>> {
    let mut rows = Vec::new();
    if !runs_dir.exists() {
        return Ok(rows);
    }
    for entry in fs::read_dir(runs_dir)? {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let dir = entry.path();
        let run_id = entry.file_name().to_string_lossy().to_string();

        let manifest = fs::read_to_string(dir.join("manifest.txt"))
            .map(|s| parse_manifest(&s))
            .unwrap_or_default();
        let headline = fs::read_to_string(dir.join("entry.md"))
            .map(|s| extract_headline(&s))
            .unwrap_or_default();

        rows.push(RunRow {
            run_id,
            sha: manifest.short_sha(),
            timestamp: manifest.timestamp().to_string(),
            headline,
        });
    }
    // newest first: run-id is `<ts>-<sha>`, sortable lexically.
    rows.sort_by(|a, b| b.run_id.cmp(&a.run_id));
    Ok(rows)
}

/// Regenerate `<journal>/INDEX.md` from the runs directory.
pub fn regenerate(journal_dir: &Path) -> std::io::Result<()> {
    let rows = collect_rows(&journal_dir.join("runs"))?;
    fs::write(journal_dir.join("INDEX.md"), render(&rows))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn headline_extracted_from_what_changed() {
        let md = "# run-1\n\n- commit: abc\n\n## What changed\nudp: batch syscalls\n\n## Hypothesis\nfaster\n";
        assert_eq!(extract_headline(md), "udp: batch syscalls");
    }

    #[test]
    fn headline_empty_when_only_placeholder_prompt() {
        let md = "## What changed\n<one-paragraph description>\n";
        assert_eq!(extract_headline(md), "");
    }

    #[test]
    fn headline_empty_when_section_absent() {
        assert_eq!(extract_headline("# run\n\n## Hypothesis\nx\n"), "");
    }

    #[test]
    fn render_has_header_and_rows_in_order() {
        let rows = vec![
            RunRow {
                run_id: "20260625T060000Z-bbb".into(),
                sha: "bbb".into(),
                timestamp: "20260625T060000Z".into(),
                headline: "second".into(),
            },
            RunRow {
                run_id: "20260625T050000Z-aaa".into(),
                sha: "aaa".into(),
                timestamp: "20260625T050000Z".into(),
                headline: "first | with pipe".into(),
            },
        ];
        let md = render(&rows);
        assert!(md.contains("| run-id | sha | timestamp | what changed |"));
        let i_b = md.find("bbb").unwrap();
        let i_a = md.find("aaa").unwrap();
        assert!(i_b < i_a, "newest-first order preserved");
        // pipe escaped in headline
        assert!(md.contains("first \\| with pipe"));
    }

    #[test]
    fn render_empty_shows_none() {
        assert!(render(&[]).contains("_(none)_"));
    }
}
