// Code generated by bebopc-go; DO NOT EDIT.

package journalbop

import (
	"github.com/200sc/bebop"
	"github.com/200sc/bebop/iohelp"
	"io"
)

var _ bebop.Record = &Entry{}

type Entry struct {
	EntryTermId    int64
	EntryIndex     int64
	EntryTimestamp int64
	CommandKey     int32
	Command        []byte
}

func (bbp Entry) MarshalBebopTo(buf []byte) int {
	at := 0
	iohelp.WriteInt64Bytes(buf[at:], bbp.EntryTermId)
	at += 8
	iohelp.WriteInt64Bytes(buf[at:], bbp.EntryIndex)
	at += 8
	iohelp.WriteInt64Bytes(buf[at:], bbp.EntryTimestamp)
	at += 8
	iohelp.WriteInt32Bytes(buf[at:], bbp.CommandKey)
	at += 4
	iohelp.WriteUint32Bytes(buf[at:], uint32(len(bbp.Command)))
	at += 4
	copy(buf[at:at+len(bbp.Command)], bbp.Command)
	at += len(bbp.Command)
	return at
}

func (bbp *Entry) UnmarshalBebop(buf []byte) (err error) {
	at := 0
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.EntryTermId = iohelp.ReadInt64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.EntryIndex = iohelp.ReadInt64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.EntryTimestamp = iohelp.ReadInt64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 4 {
		return io.ErrUnexpectedEOF
	}
	bbp.CommandKey = iohelp.ReadInt32Bytes(buf[at:])
	at += 4
	if len(buf[at:]) < 4 {
		return io.ErrUnexpectedEOF
	}
	bbp.Command = make([]byte, iohelp.ReadUint32Bytes(buf[at:]))
	at += 4
	if len(buf[at:]) < len(bbp.Command)*1 {
		return io.ErrUnexpectedEOF
	}
	copy(bbp.Command, buf[at:at+len(bbp.Command)])
	at += len(bbp.Command)
	return nil
}

func (bbp Entry) EncodeBebop(iow io.Writer) (err error) {
	w := iohelp.NewErrorWriter(iow)
	iohelp.WriteInt64(w, bbp.EntryTermId)
	iohelp.WriteInt64(w, bbp.EntryIndex)
	iohelp.WriteInt64(w, bbp.EntryTimestamp)
	iohelp.WriteInt32(w, bbp.CommandKey)
	iohelp.WriteUint32(w, uint32(len(bbp.Command)))
	w.Write(bbp.Command)
	return w.Err
}

func (bbp *Entry) DecodeBebop(ior io.Reader) (err error) {
	r := iohelp.NewErrorReader(ior)
	bbp.EntryTermId = iohelp.ReadInt64(r)
	bbp.EntryIndex = iohelp.ReadInt64(r)
	bbp.EntryTimestamp = iohelp.ReadInt64(r)
	bbp.CommandKey = iohelp.ReadInt32(r)
	bbp.Command = make([]byte, iohelp.ReadUint32(r))
	r.Read(bbp.Command)
	return r.Err
}

func (bbp Entry) Size() int {
	bodyLen := 0
	bodyLen += 8
	bodyLen += 8
	bodyLen += 8
	bodyLen += 4
	bodyLen += 4
	bodyLen += len(bbp.Command) * 1
	return bodyLen
}

func (bbp Entry) MarshalBebop() []byte {
	buf := make([]byte, bbp.Size())
	bbp.MarshalBebopTo(buf)
	return buf
}

func MakeEntry(r *iohelp.ErrorReader) (Entry, error) {
	v := Entry{}
	err := v.DecodeBebop(r)
	return v, err
}

func MakeEntryFromBytes(buf []byte) (Entry, error) {
	v := Entry{}
	err := v.UnmarshalBebop(buf)
	return v, err
}

var _ bebop.Record = &JournalRecord{}

type JournalRecord struct {
	LeadershipTermId int64
	LogPosition      int64
	Timestamp        int64
	ClusterSessionId int64
	CorrelationId    int64
	LeaderMemberId   int32
	ServiceId        int32
	EventType        byte
	RecordFlags      byte
	Entries          []Entry
}

func (bbp JournalRecord) MarshalBebopTo(buf []byte) int {
	at := 0
	iohelp.WriteInt64Bytes(buf[at:], bbp.LeadershipTermId)
	at += 8
	iohelp.WriteInt64Bytes(buf[at:], bbp.LogPosition)
	at += 8
	iohelp.WriteInt64Bytes(buf[at:], bbp.Timestamp)
	at += 8
	iohelp.WriteInt64Bytes(buf[at:], bbp.ClusterSessionId)
	at += 8
	iohelp.WriteInt64Bytes(buf[at:], bbp.CorrelationId)
	at += 8
	iohelp.WriteInt32Bytes(buf[at:], bbp.LeaderMemberId)
	at += 4
	iohelp.WriteInt32Bytes(buf[at:], bbp.ServiceId)
	at += 4
	iohelp.WriteByteBytes(buf[at:], bbp.EventType)
	at += 1
	iohelp.WriteByteBytes(buf[at:], bbp.RecordFlags)
	at += 1
	iohelp.WriteUint32Bytes(buf[at:], uint32(len(bbp.Entries)))
	at += 4
	for _, v1 := range bbp.Entries {
		(v1).MarshalBebopTo(buf[at:])
		{
			tmp := (v1)
			at += tmp.Size()
		}

	}
	return at
}

func (bbp *JournalRecord) UnmarshalBebop(buf []byte) (err error) {
	at := 0
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.LeadershipTermId = iohelp.ReadInt64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.LogPosition = iohelp.ReadInt64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.Timestamp = iohelp.ReadInt64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.ClusterSessionId = iohelp.ReadInt64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.CorrelationId = iohelp.ReadInt64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 4 {
		return io.ErrUnexpectedEOF
	}
	bbp.LeaderMemberId = iohelp.ReadInt32Bytes(buf[at:])
	at += 4
	if len(buf[at:]) < 4 {
		return io.ErrUnexpectedEOF
	}
	bbp.ServiceId = iohelp.ReadInt32Bytes(buf[at:])
	at += 4
	if len(buf[at:]) < 1 {
		return io.ErrUnexpectedEOF
	}
	bbp.EventType = iohelp.ReadByteBytes(buf[at:])
	at += 1
	if len(buf[at:]) < 1 {
		return io.ErrUnexpectedEOF
	}
	bbp.RecordFlags = iohelp.ReadByteBytes(buf[at:])
	at += 1
	if len(buf[at:]) < 4 {
		return io.ErrUnexpectedEOF
	}
	bbp.Entries = make([]Entry, iohelp.ReadUint32Bytes(buf[at:]))
	at += 4
	for i1 := range bbp.Entries {
		(bbp.Entries)[i1], err = MakeEntryFromBytes(buf[at:])
		if err != nil {
			return err
		}
		{
			tmp := ((bbp.Entries)[i1])
			at += tmp.Size()
		}

	}
	return nil
}

func (bbp JournalRecord) EncodeBebop(iow io.Writer) (err error) {
	w := iohelp.NewErrorWriter(iow)
	iohelp.WriteInt64(w, bbp.LeadershipTermId)
	iohelp.WriteInt64(w, bbp.LogPosition)
	iohelp.WriteInt64(w, bbp.Timestamp)
	iohelp.WriteInt64(w, bbp.ClusterSessionId)
	iohelp.WriteInt64(w, bbp.CorrelationId)
	iohelp.WriteInt32(w, bbp.LeaderMemberId)
	iohelp.WriteInt32(w, bbp.ServiceId)
	iohelp.WriteByte(w, bbp.EventType)
	iohelp.WriteByte(w, bbp.RecordFlags)
	iohelp.WriteUint32(w, uint32(len(bbp.Entries)))
	for _, elem := range bbp.Entries {
		err = (elem).EncodeBebop(w)
		if err != nil {
			return err
		}
	}
	return w.Err
}

func (bbp *JournalRecord) DecodeBebop(ior io.Reader) (err error) {
	r := iohelp.NewErrorReader(ior)
	bbp.LeadershipTermId = iohelp.ReadInt64(r)
	bbp.LogPosition = iohelp.ReadInt64(r)
	bbp.Timestamp = iohelp.ReadInt64(r)
	bbp.ClusterSessionId = iohelp.ReadInt64(r)
	bbp.CorrelationId = iohelp.ReadInt64(r)
	bbp.LeaderMemberId = iohelp.ReadInt32(r)
	bbp.ServiceId = iohelp.ReadInt32(r)
	bbp.EventType = iohelp.ReadByte(r)
	bbp.RecordFlags = iohelp.ReadByte(r)
	bbp.Entries = make([]Entry, iohelp.ReadUint32(r))
	for i1 := range bbp.Entries {
		(bbp.Entries[i1]), err = MakeEntry(r)
		if err != nil {
			return err
		}
	}
	return r.Err
}

func (bbp JournalRecord) Size() int {
	bodyLen := 0
	bodyLen += 8
	bodyLen += 8
	bodyLen += 8
	bodyLen += 8
	bodyLen += 8
	bodyLen += 4
	bodyLen += 4
	bodyLen += 1
	bodyLen += 1
	bodyLen += 4
	for _, elem := range bbp.Entries {
		{
			tmp := (elem)
			bodyLen += tmp.Size()
		}

	}
	return bodyLen
}

func (bbp JournalRecord) MarshalBebop() []byte {
	buf := make([]byte, bbp.Size())
	bbp.MarshalBebopTo(buf)
	return buf
}

func MakeJournalRecord(r *iohelp.ErrorReader) (JournalRecord, error) {
	v := JournalRecord{}
	err := v.DecodeBebop(r)
	return v, err
}

func MakeJournalRecordFromBytes(buf []byte) (JournalRecord, error) {
	v := JournalRecord{}
	err := v.UnmarshalBebop(buf)
	return v, err
}
