// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package journalfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Entry struct {
	_tab flatbuffers.Table
}

func GetRootAsEntry(buf []byte, offset flatbuffers.UOffsetT) *Entry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Entry{}
	x.Init(buf, n+offset)
	return x
}

func FinishEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEntry(buf []byte, offset flatbuffers.UOffsetT) *Entry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Entry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Entry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Entry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Entry) EntryTermId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateEntryTermId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *Entry) EntryIndex() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateEntryIndex(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *Entry) EntryTimestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateEntryTimestamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *Entry) CommandKey() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateCommandKey(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *Entry) CmdQty() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateCmdQty(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *Entry) CmdPrice() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Entry) MutateCmdPrice(n float64) bool {
	return rcv._tab.MutateFloat64Slot(14, n)
}

func (rcv *Entry) CmdFlag() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Entry) MutateCmdFlag(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *Entry) CmdText() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func EntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func EntryAddEntryTermId(builder *flatbuffers.Builder, entryTermId int64) {
	builder.PrependInt64Slot(0, entryTermId, 0)
}
func EntryAddEntryIndex(builder *flatbuffers.Builder, entryIndex int64) {
	builder.PrependInt64Slot(1, entryIndex, 0)
}
func EntryAddEntryTimestamp(builder *flatbuffers.Builder, entryTimestamp int64) {
	builder.PrependInt64Slot(2, entryTimestamp, 0)
}
func EntryAddCommandKey(builder *flatbuffers.Builder, commandKey int32) {
	builder.PrependInt32Slot(3, commandKey, 0)
}
func EntryAddCmdQty(builder *flatbuffers.Builder, cmdQty int64) {
	builder.PrependInt64Slot(4, cmdQty, 0)
}
func EntryAddCmdPrice(builder *flatbuffers.Builder, cmdPrice float64) {
	builder.PrependFloat64Slot(5, cmdPrice, 0.0)
}
func EntryAddCmdFlag(builder *flatbuffers.Builder, cmdFlag bool) {
	builder.PrependBoolSlot(6, cmdFlag, false)
}
func EntryAddCmdText(builder *flatbuffers.Builder, cmdText flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(cmdText), 0)
}
func EntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
