// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package journalfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type JournalRecord struct {
	_tab flatbuffers.Table
}

func GetRootAsJournalRecord(buf []byte, offset flatbuffers.UOffsetT) *JournalRecord {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JournalRecord{}
	x.Init(buf, n+offset)
	return x
}

func FinishJournalRecordBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsJournalRecord(buf []byte, offset flatbuffers.UOffsetT) *JournalRecord {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JournalRecord{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedJournalRecordBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *JournalRecord) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JournalRecord) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JournalRecord) LeadershipTermId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JournalRecord) MutateLeadershipTermId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *JournalRecord) LogPosition() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JournalRecord) MutateLogPosition(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *JournalRecord) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JournalRecord) MutateTimestamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *JournalRecord) ClusterSessionId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JournalRecord) MutateClusterSessionId(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *JournalRecord) CorrelationId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JournalRecord) MutateCorrelationId(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *JournalRecord) LeaderMemberId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JournalRecord) MutateLeaderMemberId(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *JournalRecord) ServiceId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JournalRecord) MutateServiceId(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *JournalRecord) EventType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JournalRecord) MutateEventType(n byte) bool {
	return rcv._tab.MutateByteSlot(18, n)
}

func (rcv *JournalRecord) Flags() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JournalRecord) MutateFlags(n byte) bool {
	return rcv._tab.MutateByteSlot(20, n)
}

func (rcv *JournalRecord) Entries(obj *Entry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *JournalRecord) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func JournalRecordStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func JournalRecordAddLeadershipTermId(builder *flatbuffers.Builder, leadershipTermId int64) {
	builder.PrependInt64Slot(0, leadershipTermId, 0)
}
func JournalRecordAddLogPosition(builder *flatbuffers.Builder, logPosition int64) {
	builder.PrependInt64Slot(1, logPosition, 0)
}
func JournalRecordAddTimestamp(builder *flatbuffers.Builder, timestamp int64) {
	builder.PrependInt64Slot(2, timestamp, 0)
}
func JournalRecordAddClusterSessionId(builder *flatbuffers.Builder, clusterSessionId int64) {
	builder.PrependInt64Slot(3, clusterSessionId, 0)
}
func JournalRecordAddCorrelationId(builder *flatbuffers.Builder, correlationId int64) {
	builder.PrependInt64Slot(4, correlationId, 0)
}
func JournalRecordAddLeaderMemberId(builder *flatbuffers.Builder, leaderMemberId int32) {
	builder.PrependInt32Slot(5, leaderMemberId, 0)
}
func JournalRecordAddServiceId(builder *flatbuffers.Builder, serviceId int32) {
	builder.PrependInt32Slot(6, serviceId, 0)
}
func JournalRecordAddEventType(builder *flatbuffers.Builder, eventType byte) {
	builder.PrependByteSlot(7, eventType, 0)
}
func JournalRecordAddFlags(builder *flatbuffers.Builder, flags byte) {
	builder.PrependByteSlot(8, flags, 0)
}
func JournalRecordAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(entries), 0)
}
func JournalRecordStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func JournalRecordEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
