/* Generated SBE (Simple Binary Encoding) message codec */
// Code generated by SBE. DO NOT EDIT.

package booksnap

import (
	"fmt"
	"strings"
)

type BookSnapshot struct {
	buffer            []byte
	bufferLength      uint64
	offset            uint64
	position          uint64
	actingBlockLength uint64
	actingVersion     uint64
	_Levels           BookSnapshotLevels
	_Orders           BookSnapshotOrders
}

func (m *BookSnapshot) sbePositionPtr() *uint64 {
	return &m.position
}

const (
	BookSnapshotSbeBlockLength     uint16 = uint16(40)
	BookSnapshotSbeTemplateID      uint16 = uint16(1)
	BookSnapshotSbeSchemaID        uint16 = uint16(8)
	BookSnapshotSbeSchemaVersion   uint16 = uint16(2)
	BookSnapshotSbeSemanticVersion string = ""
)

func (m *BookSnapshot) SbeBlockLength() uint16 {
	return uint16(40)
}

func (m *BookSnapshot) SbeBlockAndHeaderLength() uint64 {
	return MessageHeaderEncodedLength + uint64(m.SbeBlockLength())
}

func (m *BookSnapshot) SbeTemplateId() uint16 {
	return uint16(1)
}

func (m *BookSnapshot) SbeSchemaId() uint16 {
	return uint16(8)
}

func (m *BookSnapshot) SbeSchemaVersion() uint16 {
	return uint16(2)
}

func (m *BookSnapshot) SbeSemanticVersion() string {
	return ""
}

func (m *BookSnapshot) SbeSemanticType() string {
	return ""
}

func (m *BookSnapshot) Offset() uint64 {
	return m.offset
}

func (m *BookSnapshot) Wrap(
	buffer []byte,
	offset uint64,
	bufferLength uint64,
	actingBlockLength uint64,
	actingVersion uint64) *BookSnapshot {
	m.buffer = buffer
	m.bufferLength = bufferLength
	m.offset = offset
	m.position = m.SbeCheckPosition(offset + actingBlockLength)
	m.actingBlockLength = actingBlockLength
	m.actingVersion = actingVersion
	return m
}

func (m *BookSnapshot) WrapForEncode(buffer []byte, offset uint64, bufferLength uint64) *BookSnapshot {
	return m.Wrap(buffer, offset, bufferLength,
		uint64(m.SbeBlockLength()), uint64(m.SbeSchemaVersion()))
}

func (m *BookSnapshot) WrapAndApplyHeader(buffer []byte, offset uint64, bufferLength uint64) *BookSnapshot {
	var hdr MessageHeader
	hdr.Wrap(buffer, offset, uint64(m.SbeSchemaVersion()), bufferLength)

	hdr.SetBlockLength(m.SbeBlockLength()).
		SetTemplateId(m.SbeTemplateId()).
		SetSchemaId(m.SbeSchemaId()).
		SetVersion(m.SbeSchemaVersion())

	return m.Wrap(
		buffer,
		offset+hdr.EncodedLength(),
		bufferLength,
		uint64(m.SbeBlockLength()),
		uint64(m.SbeSchemaVersion()))
}

func (m *BookSnapshot) WrapForDecode(
	buffer []byte,
	offset uint64,
	actingBlockLength uint64,
	actingVersion uint64,
	bufferLength uint64) *BookSnapshot {
	return m.Wrap(
		buffer,
		offset,
		bufferLength,
		actingBlockLength,
		actingVersion)
}

func (m *BookSnapshot) sbeRewind() *BookSnapshot {
	return m.WrapForDecode(m.buffer, m.offset, m.actingBlockLength, m.actingVersion, m.bufferLength)
}

func (m *BookSnapshot) SbePosition() uint64 {
	return m.position
}

func (m *BookSnapshot) SbeCheckPosition(position uint64) uint64 {
	if !SbeNoBoundsCheck && (position > m.bufferLength) {
		panic("buffer too short [E100]")
	}
	return position
}

func (m *BookSnapshot) SetSbePosition(position uint64) {
	m.position = m.SbeCheckPosition(position)
}

func (m *BookSnapshot) EncodedLength() uint64 {
	return m.SbePosition() - m.offset
}

func (m *BookSnapshot) DecodeLength() uint64 {
	var skipper BookSnapshot
	skipper.WrapForDecode(m.buffer, m.offset, uint64(m.SbeBlockLength()),
		uint64(m.ActingVersion()), m.bufferLength)
	skipper.Skip()
	return skipper.EncodedLength()
}

func (m *BookSnapshot) Buffer() []byte {
	return m.buffer
}

func (m *BookSnapshot) BufferLength() uint64 {
	return m.bufferLength
}

func (m *BookSnapshot) ActingVersion() uint64 {
	return m.actingVersion
}

func (m *BookSnapshot) PriceMinMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshot) PriceMinId() int {
	return 1
}

func (m *BookSnapshot) PriceMinSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshot) PriceMinInActingVersion() bool {
	return true
}

func (m *BookSnapshot) PriceMinEncodingOffset() uint {
	return 0
}

func (m *BookSnapshot) PriceMinNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *BookSnapshot) PriceMinMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *BookSnapshot) PriceMinMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *BookSnapshot) PriceMinEncodingLength() int {
	return 8
}

func (m *BookSnapshot) PriceMin() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 0):])
}

func (m *BookSnapshot) SetPriceMin(value int64) *BookSnapshot {
	PutInt64LittleEndian(m.buffer[(m.offset+0):], value)
	return m
}

func (m *BookSnapshot) TickSizeMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshot) TickSizeId() int {
	return 2
}

func (m *BookSnapshot) TickSizeSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshot) TickSizeInActingVersion() bool {
	return true
}

func (m *BookSnapshot) TickSizeEncodingOffset() uint {
	return 8
}

func (m *BookSnapshot) TickSizeNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *BookSnapshot) TickSizeMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *BookSnapshot) TickSizeMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *BookSnapshot) TickSizeEncodingLength() int {
	return 8
}

func (m *BookSnapshot) TickSize() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 8):])
}

func (m *BookSnapshot) SetTickSize(value int64) *BookSnapshot {
	PutInt64LittleEndian(m.buffer[(m.offset+8):], value)
	return m
}

func (m *BookSnapshot) NLevelsMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshot) NLevelsId() int {
	return 3
}

func (m *BookSnapshot) NLevelsSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshot) NLevelsInActingVersion() bool {
	return true
}

func (m *BookSnapshot) NLevelsEncodingOffset() uint {
	return 16
}

func (m *BookSnapshot) NLevelsNullValue() uint32 {
	return SbeNullValueUint32()
}

func (m *BookSnapshot) NLevelsMinValue() uint32 {
	return uint32(0x0)
}

func (m *BookSnapshot) NLevelsMaxValue() uint32 {
	return uint32(0xfffffffe)
}

func (m *BookSnapshot) NLevelsEncodingLength() int {
	return 4
}

func (m *BookSnapshot) NLevels() uint32 {
	return Uint32LittleEndian(m.buffer[(m.offset + 16):])
}

func (m *BookSnapshot) SetNLevels(value uint32) *BookSnapshot {
	PutUint32LittleEndian(m.buffer[(m.offset+16):], value)
	return m
}

func (m *BookSnapshot) CapacityMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshot) CapacityId() int {
	return 4
}

func (m *BookSnapshot) CapacitySinceVersion() uint64 {
	return 0
}

func (m *BookSnapshot) CapacityInActingVersion() bool {
	return true
}

func (m *BookSnapshot) CapacityEncodingOffset() uint {
	return 20
}

func (m *BookSnapshot) CapacityNullValue() uint32 {
	return SbeNullValueUint32()
}

func (m *BookSnapshot) CapacityMinValue() uint32 {
	return uint32(0x0)
}

func (m *BookSnapshot) CapacityMaxValue() uint32 {
	return uint32(0xfffffffe)
}

func (m *BookSnapshot) CapacityEncodingLength() int {
	return 4
}

func (m *BookSnapshot) Capacity() uint32 {
	return Uint32LittleEndian(m.buffer[(m.offset + 20):])
}

func (m *BookSnapshot) SetCapacity(value uint32) *BookSnapshot {
	PutUint32LittleEndian(m.buffer[(m.offset+20):], value)
	return m
}

func (m *BookSnapshot) HwmMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshot) HwmId() int {
	return 5
}

func (m *BookSnapshot) HwmSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshot) HwmInActingVersion() bool {
	return true
}

func (m *BookSnapshot) HwmEncodingOffset() uint {
	return 24
}

func (m *BookSnapshot) HwmNullValue() uint32 {
	return SbeNullValueUint32()
}

func (m *BookSnapshot) HwmMinValue() uint32 {
	return uint32(0x0)
}

func (m *BookSnapshot) HwmMaxValue() uint32 {
	return uint32(0xfffffffe)
}

func (m *BookSnapshot) HwmEncodingLength() int {
	return 4
}

func (m *BookSnapshot) Hwm() uint32 {
	return Uint32LittleEndian(m.buffer[(m.offset + 24):])
}

func (m *BookSnapshot) SetHwm(value uint32) *BookSnapshot {
	PutUint32LittleEndian(m.buffer[(m.offset+24):], value)
	return m
}

func (m *BookSnapshot) BestBidMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshot) BestBidId() int {
	return 6
}

func (m *BookSnapshot) BestBidSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshot) BestBidInActingVersion() bool {
	return true
}

func (m *BookSnapshot) BestBidEncodingOffset() uint {
	return 28
}

func (m *BookSnapshot) BestBidNullValue() int32 {
	return SbeNullValueInt32()
}

func (m *BookSnapshot) BestBidMinValue() int32 {
	return int32(-2147483647)
}

func (m *BookSnapshot) BestBidMaxValue() int32 {
	return int32(2147483647)
}

func (m *BookSnapshot) BestBidEncodingLength() int {
	return 4
}

func (m *BookSnapshot) BestBid() int32 {
	return Int32LittleEndian(m.buffer[(m.offset + 28):])
}

func (m *BookSnapshot) SetBestBid(value int32) *BookSnapshot {
	PutInt32LittleEndian(m.buffer[(m.offset+28):], value)
	return m
}

func (m *BookSnapshot) BestAskMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshot) BestAskId() int {
	return 7
}

func (m *BookSnapshot) BestAskSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshot) BestAskInActingVersion() bool {
	return true
}

func (m *BookSnapshot) BestAskEncodingOffset() uint {
	return 32
}

func (m *BookSnapshot) BestAskNullValue() int32 {
	return SbeNullValueInt32()
}

func (m *BookSnapshot) BestAskMinValue() int32 {
	return int32(-2147483647)
}

func (m *BookSnapshot) BestAskMaxValue() int32 {
	return int32(2147483647)
}

func (m *BookSnapshot) BestAskEncodingLength() int {
	return 4
}

func (m *BookSnapshot) BestAsk() int32 {
	return Int32LittleEndian(m.buffer[(m.offset + 32):])
}

func (m *BookSnapshot) SetBestAsk(value int32) *BookSnapshot {
	PutInt32LittleEndian(m.buffer[(m.offset+32):], value)
	return m
}

func (m *BookSnapshot) FreeHeadMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshot) FreeHeadId() int {
	return 8
}

func (m *BookSnapshot) FreeHeadSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshot) FreeHeadInActingVersion() bool {
	return true
}

func (m *BookSnapshot) FreeHeadEncodingOffset() uint {
	return 36
}

func (m *BookSnapshot) FreeHeadNullValue() uint32 {
	return SbeNullValueUint32()
}

func (m *BookSnapshot) FreeHeadMinValue() uint32 {
	return uint32(0x0)
}

func (m *BookSnapshot) FreeHeadMaxValue() uint32 {
	return uint32(0xfffffffe)
}

func (m *BookSnapshot) FreeHeadEncodingLength() int {
	return 4
}

func (m *BookSnapshot) FreeHead() uint32 {
	return Uint32LittleEndian(m.buffer[(m.offset + 36):])
}

func (m *BookSnapshot) SetFreeHead(value uint32) *BookSnapshot {
	PutUint32LittleEndian(m.buffer[(m.offset+36):], value)
	return m
}

type BookSnapshotLevels struct {
	buffer          []byte
	bufferLength    uint64
	initialPosition uint64
	positionPtr     *uint64
	blockLength     uint64
	count           uint64
	index           uint64
	offset          uint64
	actingVersion   uint64
}

func (g *BookSnapshotLevels) sbePositionPtr() *uint64 {
	return g.positionPtr
}

func (g *BookSnapshotLevels) WrapForDecode(
	buffer []byte,
	pos *uint64,
	actingVersion uint64,
	bufferLength uint64) {
	dimensions := GroupSizeEncoding{}
	dimensions.Wrap(buffer, *pos, actingVersion, bufferLength)
	g.buffer = buffer
	g.bufferLength = bufferLength
	g.blockLength = uint64(dimensions.BlockLength())
	g.count = uint64(dimensions.NumInGroup())
	g.index = 0
	g.actingVersion = actingVersion
	g.initialPosition = *pos
	g.positionPtr = pos
	*g.positionPtr = *g.positionPtr + 4
}

func (g *BookSnapshotLevels) WrapForEncode(
	buffer []byte,
	count uint16,
	pos *uint64,
	actingVersion uint64,
	bufferLength uint64) {
	if count > 65534 {
		panic("count outside of allowed range [E110]")
	}
	g.buffer = buffer
	g.bufferLength = bufferLength
	dimensions := GroupSizeEncoding{}
	dimensions.Wrap(buffer, *pos, actingVersion, bufferLength)
	dimensions.SetBlockLength(25)
	dimensions.SetNumInGroup(count)
	g.index = 0
	g.count = uint64(count)
	g.blockLength = 25
	g.actingVersion = actingVersion
	g.initialPosition = *pos
	g.positionPtr = pos
	*g.positionPtr = *g.positionPtr + 4
}

func (g *BookSnapshotLevels) SbeHeaderSize() uint64 {
	return 4
}

func (g *BookSnapshotLevels) SbeBlockLength() uint64 {
	return 25
}

func (g *BookSnapshotLevels) SbePosition() uint64 {
	return *g.positionPtr
}

func (g *BookSnapshotLevels) SbeCheckPosition(position uint64) uint64 {
	if position > g.bufferLength {
		panic("buffer too short [E100]")
	}
	return position
}

func (g *BookSnapshotLevels) SetSbePosition(position uint64) {
	*g.positionPtr = g.SbeCheckPosition(position)
}

func (g *BookSnapshotLevels) Count() uint64 {
	return g.count
}

func (g *BookSnapshotLevels) HasNext() bool {
	return g.index < g.count
}

func (g *BookSnapshotLevels) Next() *BookSnapshotLevels {
	if g.index >= g.count {
		panic("index >= count [E108]")
	}
	g.offset = *g.positionPtr
	if g.offset+g.blockLength > g.bufferLength {
		panic("buffer too short for next group index [E108]")
	}
	*g.positionPtr = g.offset + g.blockLength
	g.index++

	return g
}

func (g *BookSnapshotLevels) ResetCountToIndex() uint64 {
	g.count = g.index
	dimensions := GroupSizeEncoding{}
	dimensions.Wrap(g.buffer, g.initialPosition, g.actingVersion, g.bufferLength)
	dimensions.SetNumInGroup(uint16(g.count))
	return g.count
}

func (g *BookSnapshotLevels) ForEach(fn func(group *BookSnapshotLevels)) {
	for g.HasNext() {
		g.Next()
		fn(g)
	}
}

func (m *BookSnapshotLevels) SideMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotLevels) SideId() int {
	return 11
}

func (m *BookSnapshotLevels) SideSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotLevels) SideInActingVersion() bool {
	return true
}

func (m *BookSnapshotLevels) SideEncodingOffset() uint {
	return 0
}

func (m *BookSnapshotLevels) SideEncodingLength() int {
	return 1
}

func (m *BookSnapshotLevels) SideRaw() uint8 {
	return Uint8LittleEndian(m.buffer[(m.offset + 0):])
}

func (m *BookSnapshotLevels) Side() Side {
	return Side(Uint8LittleEndian(m.buffer[(m.offset + 0):]))
}

func (m *BookSnapshotLevels) SetSide(value Side) *BookSnapshotLevels {
	val := uint8(value)
	PutUint8LittleEndian(m.buffer[(m.offset+0):], val)
	return m
}

func (m *BookSnapshotLevels) LevelTickMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotLevels) LevelTickId() int {
	return 12
}

func (m *BookSnapshotLevels) LevelTickSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotLevels) LevelTickInActingVersion() bool {
	return true
}

func (m *BookSnapshotLevels) LevelTickEncodingOffset() uint {
	return 1
}

func (m *BookSnapshotLevels) LevelTickNullValue() uint32 {
	return SbeNullValueUint32()
}

func (m *BookSnapshotLevels) LevelTickMinValue() uint32 {
	return uint32(0x0)
}

func (m *BookSnapshotLevels) LevelTickMaxValue() uint32 {
	return uint32(0xfffffffe)
}

func (m *BookSnapshotLevels) LevelTickEncodingLength() int {
	return 4
}

func (m *BookSnapshotLevels) LevelTick() uint32 {
	return Uint32LittleEndian(m.buffer[(m.offset + 1):])
}

func (m *BookSnapshotLevels) SetLevelTick(value uint32) *BookSnapshotLevels {
	PutUint32LittleEndian(m.buffer[(m.offset+1):], value)
	return m
}

func (m *BookSnapshotLevels) QtyTotalMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotLevels) QtyTotalId() int {
	return 13
}

func (m *BookSnapshotLevels) QtyTotalSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotLevels) QtyTotalInActingVersion() bool {
	return true
}

func (m *BookSnapshotLevels) QtyTotalEncodingOffset() uint {
	return 5
}

func (m *BookSnapshotLevels) QtyTotalNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *BookSnapshotLevels) QtyTotalMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *BookSnapshotLevels) QtyTotalMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *BookSnapshotLevels) QtyTotalEncodingLength() int {
	return 8
}

func (m *BookSnapshotLevels) QtyTotal() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 5):])
}

func (m *BookSnapshotLevels) SetQtyTotal(value int64) *BookSnapshotLevels {
	PutInt64LittleEndian(m.buffer[(m.offset+5):], value)
	return m
}

func (m *BookSnapshotLevels) OrderCountMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotLevels) OrderCountId() int {
	return 14
}

func (m *BookSnapshotLevels) OrderCountSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotLevels) OrderCountInActingVersion() bool {
	return true
}

func (m *BookSnapshotLevels) OrderCountEncodingOffset() uint {
	return 13
}

func (m *BookSnapshotLevels) OrderCountNullValue() uint32 {
	return SbeNullValueUint32()
}

func (m *BookSnapshotLevels) OrderCountMinValue() uint32 {
	return uint32(0x0)
}

func (m *BookSnapshotLevels) OrderCountMaxValue() uint32 {
	return uint32(0xfffffffe)
}

func (m *BookSnapshotLevels) OrderCountEncodingLength() int {
	return 4
}

func (m *BookSnapshotLevels) OrderCount() uint32 {
	return Uint32LittleEndian(m.buffer[(m.offset + 13):])
}

func (m *BookSnapshotLevels) SetOrderCount(value uint32) *BookSnapshotLevels {
	PutUint32LittleEndian(m.buffer[(m.offset+13):], value)
	return m
}

func (m *BookSnapshotLevels) HeadMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotLevels) HeadId() int {
	return 15
}

func (m *BookSnapshotLevels) HeadSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotLevels) HeadInActingVersion() bool {
	return true
}

func (m *BookSnapshotLevels) HeadEncodingOffset() uint {
	return 17
}

func (m *BookSnapshotLevels) HeadNullValue() uint32 {
	return SbeNullValueUint32()
}

func (m *BookSnapshotLevels) HeadMinValue() uint32 {
	return uint32(0x0)
}

func (m *BookSnapshotLevels) HeadMaxValue() uint32 {
	return uint32(0xfffffffe)
}

func (m *BookSnapshotLevels) HeadEncodingLength() int {
	return 4
}

func (m *BookSnapshotLevels) Head() uint32 {
	return Uint32LittleEndian(m.buffer[(m.offset + 17):])
}

func (m *BookSnapshotLevels) SetHead(value uint32) *BookSnapshotLevels {
	PutUint32LittleEndian(m.buffer[(m.offset+17):], value)
	return m
}

func (m *BookSnapshotLevels) TailMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotLevels) TailId() int {
	return 16
}

func (m *BookSnapshotLevels) TailSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotLevels) TailInActingVersion() bool {
	return true
}

func (m *BookSnapshotLevels) TailEncodingOffset() uint {
	return 21
}

func (m *BookSnapshotLevels) TailNullValue() uint32 {
	return SbeNullValueUint32()
}

func (m *BookSnapshotLevels) TailMinValue() uint32 {
	return uint32(0x0)
}

func (m *BookSnapshotLevels) TailMaxValue() uint32 {
	return uint32(0xfffffffe)
}

func (m *BookSnapshotLevels) TailEncodingLength() int {
	return 4
}

func (m *BookSnapshotLevels) Tail() uint32 {
	return Uint32LittleEndian(m.buffer[(m.offset + 21):])
}

func (m *BookSnapshotLevels) SetTail(value uint32) *BookSnapshotLevels {
	PutUint32LittleEndian(m.buffer[(m.offset+21):], value)
	return m
}

func (writer *BookSnapshotLevels) String() string {
	builder := strings.Builder{}
	builder.WriteString("{")
	builder.WriteString(`"side": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Side()))

	builder.WriteString(", ")
	builder.WriteString(`"levelTick": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.LevelTick()))

	builder.WriteString(", ")
	builder.WriteString(`"qtyTotal": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.QtyTotal()))

	builder.WriteString(", ")
	builder.WriteString(`"orderCount": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.OrderCount()))

	builder.WriteString(", ")
	builder.WriteString(`"head": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Head()))

	builder.WriteString(", ")
	builder.WriteString(`"tail": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Tail()))

	builder.WriteString("}")

	return builder.String()
}

func (m *BookSnapshotLevels) Skip() {
}

func (m *BookSnapshotLevels) IsConstLength() bool {
	return true
}

func (m *BookSnapshotLevels) ComputeLength() (int, error) {
	length := uint64(m.SbeBlockLength())

	return int(length), nil
}
func (m *BookSnapshot) LevelsId() int {
	return 10
}

func (m *BookSnapshot) Levels() *BookSnapshotLevels {
	m._Levels.WrapForDecode(m.buffer, m.sbePositionPtr(), m.actingVersion, m.bufferLength)
	return &m._Levels
}

func (m *BookSnapshot) LevelsCount(count uint16) *BookSnapshotLevels {
	m._Levels.WrapForEncode(m.buffer, count, m.sbePositionPtr(), m.actingVersion, m.bufferLength)
	return &m._Levels
}

func (m *BookSnapshot) LevelsSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshot) LevelsInActingVersion() bool {
	return true
}

type BookSnapshotOrders struct {
	buffer          []byte
	bufferLength    uint64
	initialPosition uint64
	positionPtr     *uint64
	blockLength     uint64
	count           uint64
	index           uint64
	offset          uint64
	actingVersion   uint64
}

func (g *BookSnapshotOrders) sbePositionPtr() *uint64 {
	return g.positionPtr
}

func (g *BookSnapshotOrders) WrapForDecode(
	buffer []byte,
	pos *uint64,
	actingVersion uint64,
	bufferLength uint64) {
	dimensions := GroupSizeEncoding{}
	dimensions.Wrap(buffer, *pos, actingVersion, bufferLength)
	g.buffer = buffer
	g.bufferLength = bufferLength
	g.blockLength = uint64(dimensions.BlockLength())
	g.count = uint64(dimensions.NumInGroup())
	g.index = 0
	g.actingVersion = actingVersion
	g.initialPosition = *pos
	g.positionPtr = pos
	*g.positionPtr = *g.positionPtr + 4
}

func (g *BookSnapshotOrders) WrapForEncode(
	buffer []byte,
	count uint16,
	pos *uint64,
	actingVersion uint64,
	bufferLength uint64) {
	if count > 65534 {
		panic("count outside of allowed range [E110]")
	}
	g.buffer = buffer
	g.bufferLength = bufferLength
	dimensions := GroupSizeEncoding{}
	dimensions.Wrap(buffer, *pos, actingVersion, bufferLength)
	dimensions.SetBlockLength(45)
	dimensions.SetNumInGroup(count)
	g.index = 0
	g.count = uint64(count)
	g.blockLength = 45
	g.actingVersion = actingVersion
	g.initialPosition = *pos
	g.positionPtr = pos
	*g.positionPtr = *g.positionPtr + 4
}

func (g *BookSnapshotOrders) SbeHeaderSize() uint64 {
	return 4
}

func (g *BookSnapshotOrders) SbeBlockLength() uint64 {
	return 45
}

func (g *BookSnapshotOrders) SbePosition() uint64 {
	return *g.positionPtr
}

func (g *BookSnapshotOrders) SbeCheckPosition(position uint64) uint64 {
	if position > g.bufferLength {
		panic("buffer too short [E100]")
	}
	return position
}

func (g *BookSnapshotOrders) SetSbePosition(position uint64) {
	*g.positionPtr = g.SbeCheckPosition(position)
}

func (g *BookSnapshotOrders) Count() uint64 {
	return g.count
}

func (g *BookSnapshotOrders) HasNext() bool {
	return g.index < g.count
}

func (g *BookSnapshotOrders) Next() *BookSnapshotOrders {
	if g.index >= g.count {
		panic("index >= count [E108]")
	}
	g.offset = *g.positionPtr
	if g.offset+g.blockLength > g.bufferLength {
		panic("buffer too short for next group index [E108]")
	}
	*g.positionPtr = g.offset + g.blockLength
	g.index++

	return g
}

func (g *BookSnapshotOrders) ResetCountToIndex() uint64 {
	g.count = g.index
	dimensions := GroupSizeEncoding{}
	dimensions.Wrap(g.buffer, g.initialPosition, g.actingVersion, g.bufferLength)
	dimensions.SetNumInGroup(uint16(g.count))
	return g.count
}

func (g *BookSnapshotOrders) ForEach(fn func(group *BookSnapshotOrders)) {
	for g.HasNext() {
		g.Next()
		fn(g)
	}
}

func (m *BookSnapshotOrders) SlotMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotOrders) SlotId() int {
	return 21
}

func (m *BookSnapshotOrders) SlotSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotOrders) SlotInActingVersion() bool {
	return true
}

func (m *BookSnapshotOrders) SlotEncodingOffset() uint {
	return 0
}

func (m *BookSnapshotOrders) SlotNullValue() uint32 {
	return SbeNullValueUint32()
}

func (m *BookSnapshotOrders) SlotMinValue() uint32 {
	return uint32(0x0)
}

func (m *BookSnapshotOrders) SlotMaxValue() uint32 {
	return uint32(0xfffffffe)
}

func (m *BookSnapshotOrders) SlotEncodingLength() int {
	return 4
}

func (m *BookSnapshotOrders) Slot() uint32 {
	return Uint32LittleEndian(m.buffer[(m.offset + 0):])
}

func (m *BookSnapshotOrders) SetSlot(value uint32) *BookSnapshotOrders {
	PutUint32LittleEndian(m.buffer[(m.offset+0):], value)
	return m
}

func (m *BookSnapshotOrders) OrderIdMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotOrders) OrderIdId() int {
	return 22
}

func (m *BookSnapshotOrders) OrderIdSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotOrders) OrderIdInActingVersion() bool {
	return true
}

func (m *BookSnapshotOrders) OrderIdEncodingOffset() uint {
	return 4
}

func (m *BookSnapshotOrders) OrderIdNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *BookSnapshotOrders) OrderIdMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *BookSnapshotOrders) OrderIdMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *BookSnapshotOrders) OrderIdEncodingLength() int {
	return 8
}

func (m *BookSnapshotOrders) OrderId() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 4):])
}

func (m *BookSnapshotOrders) SetOrderId(value int64) *BookSnapshotOrders {
	PutInt64LittleEndian(m.buffer[(m.offset+4):], value)
	return m
}

func (m *BookSnapshotOrders) PriceMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotOrders) PriceId() int {
	return 23
}

func (m *BookSnapshotOrders) PriceSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotOrders) PriceInActingVersion() bool {
	return true
}

func (m *BookSnapshotOrders) PriceEncodingOffset() uint {
	return 12
}

func (m *BookSnapshotOrders) PriceNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *BookSnapshotOrders) PriceMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *BookSnapshotOrders) PriceMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *BookSnapshotOrders) PriceEncodingLength() int {
	return 8
}

func (m *BookSnapshotOrders) Price() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 12):])
}

func (m *BookSnapshotOrders) SetPrice(value int64) *BookSnapshotOrders {
	PutInt64LittleEndian(m.buffer[(m.offset+12):], value)
	return m
}

func (m *BookSnapshotOrders) QtyMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotOrders) QtyId() int {
	return 24
}

func (m *BookSnapshotOrders) QtySinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotOrders) QtyInActingVersion() bool {
	return true
}

func (m *BookSnapshotOrders) QtyEncodingOffset() uint {
	return 20
}

func (m *BookSnapshotOrders) QtyNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *BookSnapshotOrders) QtyMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *BookSnapshotOrders) QtyMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *BookSnapshotOrders) QtyEncodingLength() int {
	return 8
}

func (m *BookSnapshotOrders) Qty() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 20):])
}

func (m *BookSnapshotOrders) SetQty(value int64) *BookSnapshotOrders {
	PutInt64LittleEndian(m.buffer[(m.offset+20):], value)
	return m
}

func (m *BookSnapshotOrders) FilledMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotOrders) FilledId() int {
	return 25
}

func (m *BookSnapshotOrders) FilledSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotOrders) FilledInActingVersion() bool {
	return true
}

func (m *BookSnapshotOrders) FilledEncodingOffset() uint {
	return 28
}

func (m *BookSnapshotOrders) FilledNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *BookSnapshotOrders) FilledMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *BookSnapshotOrders) FilledMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *BookSnapshotOrders) FilledEncodingLength() int {
	return 8
}

func (m *BookSnapshotOrders) Filled() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 28):])
}

func (m *BookSnapshotOrders) SetFilled(value int64) *BookSnapshotOrders {
	PutInt64LittleEndian(m.buffer[(m.offset+28):], value)
	return m
}

func (m *BookSnapshotOrders) SideMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotOrders) SideId() int {
	return 26
}

func (m *BookSnapshotOrders) SideSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotOrders) SideInActingVersion() bool {
	return true
}

func (m *BookSnapshotOrders) SideEncodingOffset() uint {
	return 36
}

func (m *BookSnapshotOrders) SideEncodingLength() int {
	return 1
}

func (m *BookSnapshotOrders) SideRaw() uint8 {
	return Uint8LittleEndian(m.buffer[(m.offset + 36):])
}

func (m *BookSnapshotOrders) Side() Side {
	return Side(Uint8LittleEndian(m.buffer[(m.offset + 36):]))
}

func (m *BookSnapshotOrders) SetSide(value Side) *BookSnapshotOrders {
	val := uint8(value)
	PutUint8LittleEndian(m.buffer[(m.offset+36):], val)
	return m
}

func (m *BookSnapshotOrders) NextSlotMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotOrders) NextSlotId() int {
	return 27
}

func (m *BookSnapshotOrders) NextSlotSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotOrders) NextSlotInActingVersion() bool {
	return true
}

func (m *BookSnapshotOrders) NextSlotEncodingOffset() uint {
	return 37
}

func (m *BookSnapshotOrders) NextSlotNullValue() uint32 {
	return SbeNullValueUint32()
}

func (m *BookSnapshotOrders) NextSlotMinValue() uint32 {
	return uint32(0x0)
}

func (m *BookSnapshotOrders) NextSlotMaxValue() uint32 {
	return uint32(0xfffffffe)
}

func (m *BookSnapshotOrders) NextSlotEncodingLength() int {
	return 4
}

func (m *BookSnapshotOrders) NextSlot() uint32 {
	return Uint32LittleEndian(m.buffer[(m.offset + 37):])
}

func (m *BookSnapshotOrders) SetNextSlot(value uint32) *BookSnapshotOrders {
	PutUint32LittleEndian(m.buffer[(m.offset+37):], value)
	return m
}

func (m *BookSnapshotOrders) PrevMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *BookSnapshotOrders) PrevId() int {
	return 28
}

func (m *BookSnapshotOrders) PrevSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshotOrders) PrevInActingVersion() bool {
	return true
}

func (m *BookSnapshotOrders) PrevEncodingOffset() uint {
	return 41
}

func (m *BookSnapshotOrders) PrevNullValue() uint32 {
	return SbeNullValueUint32()
}

func (m *BookSnapshotOrders) PrevMinValue() uint32 {
	return uint32(0x0)
}

func (m *BookSnapshotOrders) PrevMaxValue() uint32 {
	return uint32(0xfffffffe)
}

func (m *BookSnapshotOrders) PrevEncodingLength() int {
	return 4
}

func (m *BookSnapshotOrders) Prev() uint32 {
	return Uint32LittleEndian(m.buffer[(m.offset + 41):])
}

func (m *BookSnapshotOrders) SetPrev(value uint32) *BookSnapshotOrders {
	PutUint32LittleEndian(m.buffer[(m.offset+41):], value)
	return m
}

func (writer *BookSnapshotOrders) String() string {
	builder := strings.Builder{}
	builder.WriteString("{")
	builder.WriteString(`"slot": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Slot()))

	builder.WriteString(", ")
	builder.WriteString(`"orderId": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.OrderId()))

	builder.WriteString(", ")
	builder.WriteString(`"price": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Price()))

	builder.WriteString(", ")
	builder.WriteString(`"qty": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Qty()))

	builder.WriteString(", ")
	builder.WriteString(`"filled": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Filled()))

	builder.WriteString(", ")
	builder.WriteString(`"side": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Side()))

	builder.WriteString(", ")
	builder.WriteString(`"nextSlot": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.NextSlot()))

	builder.WriteString(", ")
	builder.WriteString(`"prev": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Prev()))

	builder.WriteString("}")

	return builder.String()
}

func (m *BookSnapshotOrders) Skip() {
}

func (m *BookSnapshotOrders) IsConstLength() bool {
	return true
}

func (m *BookSnapshotOrders) ComputeLength() (int, error) {
	length := uint64(m.SbeBlockLength())

	return int(length), nil
}
func (m *BookSnapshot) OrdersId() int {
	return 20
}

func (m *BookSnapshot) Orders() *BookSnapshotOrders {
	m._Orders.WrapForDecode(m.buffer, m.sbePositionPtr(), m.actingVersion, m.bufferLength)
	return &m._Orders
}

func (m *BookSnapshot) OrdersCount(count uint16) *BookSnapshotOrders {
	m._Orders.WrapForEncode(m.buffer, count, m.sbePositionPtr(), m.actingVersion, m.bufferLength)
	return &m._Orders
}

func (m *BookSnapshot) OrdersSinceVersion() uint64 {
	return 0
}

func (m *BookSnapshot) OrdersInActingVersion() bool {
	return true
}

func (writer *BookSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("{\"Name\": \"BookSnapshot\", ")
	builder.WriteString(fmt.Sprintf("\"sbeTemplateId\": %d", writer.SbeTemplateId()))
	builder.WriteString(", ")

	builder.WriteString(`"priceMin": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.PriceMin()))

	builder.WriteString(", ")
	builder.WriteString(`"tickSize": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.TickSize()))

	builder.WriteString(", ")
	builder.WriteString(`"nLevels": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.NLevels()))

	builder.WriteString(", ")
	builder.WriteString(`"capacity": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Capacity()))

	builder.WriteString(", ")
	builder.WriteString(`"hwm": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Hwm()))

	builder.WriteString(", ")
	builder.WriteString(`"bestBid": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.BestBid()))

	builder.WriteString(", ")
	builder.WriteString(`"bestAsk": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.BestAsk()))

	builder.WriteString(", ")
	builder.WriteString(`"freeHead": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.FreeHead()))

	builder.WriteString(", ")
	{
		atLeastOne := false
		builder.WriteString(`"levels": [`)
		writer.Levels().ForEach(
			func(value *BookSnapshotLevels) {
				if atLeastOne {
					builder.WriteString(", ")
				}
				atLeastOne = true
				builder.WriteString(value.String())
			})
		builder.WriteString("]")
	}

	builder.WriteString(", ")
	{
		atLeastOne := false
		builder.WriteString(`"orders": [`)
		writer.Orders().ForEach(
			func(value *BookSnapshotOrders) {
				if atLeastOne {
					builder.WriteString(", ")
				}
				atLeastOne = true
				builder.WriteString(value.String())
			})
		builder.WriteString("]")
	}

	builder.WriteString("}")

	return builder.String()
}

func (m *BookSnapshot) Skip() {
	for LevelsGroup := m.Levels(); LevelsGroup.HasNext(); {
		LevelsGroup.Next().Skip()
	}
	for OrdersGroup := m.Orders(); OrdersGroup.HasNext(); {
		OrdersGroup.Next().Skip()
	}
}

func (m *BookSnapshot) IsConstLength() bool {
	return false
}

func (m *BookSnapshot) ComputeLength(
	LevelsLength int,
	OrdersLength int) (int, error) {
	length := uint64(m.SbeBlockLength())

	length += m.Levels().SbeHeaderSize()
	if LevelsLength > 65534 {
		panic(fmt.Sprintf("LevelsLength outside of allowed range [E110]"))
	}
	length += uint64(LevelsLength) * m.Levels().SbeBlockLength()

	length += m.Orders().SbeHeaderSize()
	if OrdersLength > 65534 {
		panic(fmt.Sprintf("OrdersLength outside of allowed range [E110]"))
	}
	length += uint64(OrdersLength) * m.Orders().SbeBlockLength()

	return int(length), nil
}
