/* Generated SBE (Simple Binary Encoding) message codec */
// Code generated by SBE. DO NOT EDIT.

package booksnap

import (
	"errors"
	"fmt"
)

type Side uint8

const (
	Side_BID        Side = Side(uint8(0))
	Side_ASK        Side = Side(uint8(1))
	Side_NULL_VALUE Side = Side(uint8(255))
)

var SideLookupErr = errors.New("unknown value for enum Side [E103]")

func LookupSide(value uint8) (Side, error) {
	switch value {
	case uint8(0):
		return Side_BID, nil
	case uint8(1):
		return Side_ASK, nil
	case uint8(255):
		return Side_NULL_VALUE, nil
	}

	return 0, SideLookupErr
}

func (value Side) String() string {
	switch value {
	case Side_BID:
		return "BID"
	case Side_ASK:
		return "ASK"
	case Side_NULL_VALUE:
		return "NULL_VALUE"
	}

	panic(fmt.Sprintf("unknown value for enum Side [E103]: %d", value))
}
