// The serialization focus area's JournalRecord (see the 2026-07-16 design
// spec). sfixed64/sfixed32 by design: the ids/timestamps are full-width
// mixed bit patterns, where default varints would encode ~10 bytes/field.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: schema/journal.proto

package journalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntryTermId    int64                  `protobuf:"fixed64,1,opt,name=entry_term_id,json=entryTermId,proto3" json:"entry_term_id,omitempty"`
	EntryIndex     int64                  `protobuf:"fixed64,2,opt,name=entry_index,json=entryIndex,proto3" json:"entry_index,omitempty"`
	EntryTimestamp int64                  `protobuf:"fixed64,3,opt,name=entry_timestamp,json=entryTimestamp,proto3" json:"entry_timestamp,omitempty"`
	CommandKey     int32                  `protobuf:"fixed32,4,opt,name=command_key,json=commandKey,proto3" json:"command_key,omitempty"`
	Command        []byte                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_schema_journal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_schema_journal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_schema_journal_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetEntryTermId() int64 {
	if x != nil {
		return x.EntryTermId
	}
	return 0
}

func (x *Entry) GetEntryIndex() int64 {
	if x != nil {
		return x.EntryIndex
	}
	return 0
}

func (x *Entry) GetEntryTimestamp() int64 {
	if x != nil {
		return x.EntryTimestamp
	}
	return 0
}

func (x *Entry) GetCommandKey() int32 {
	if x != nil {
		return x.CommandKey
	}
	return 0
}

func (x *Entry) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type JournalRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LeadershipTermId int64                  `protobuf:"fixed64,1,opt,name=leadership_term_id,json=leadershipTermId,proto3" json:"leadership_term_id,omitempty"`
	LogPosition      int64                  `protobuf:"fixed64,2,opt,name=log_position,json=logPosition,proto3" json:"log_position,omitempty"`
	Timestamp        int64                  `protobuf:"fixed64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClusterSessionId int64                  `protobuf:"fixed64,4,opt,name=cluster_session_id,json=clusterSessionId,proto3" json:"cluster_session_id,omitempty"`
	CorrelationId    int64                  `protobuf:"fixed64,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	LeaderMemberId   int32                  `protobuf:"fixed32,6,opt,name=leader_member_id,json=leaderMemberId,proto3" json:"leader_member_id,omitempty"`
	ServiceId        int32                  `protobuf:"fixed32,7,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	EventType        uint32                 `protobuf:"varint,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Flags            uint32                 `protobuf:"varint,9,opt,name=flags,proto3" json:"flags,omitempty"`
	Entries          []*Entry               `protobuf:"bytes,10,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JournalRecord) Reset() {
	*x = JournalRecord{}
	mi := &file_schema_journal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalRecord) ProtoMessage() {}

func (x *JournalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_schema_journal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalRecord.ProtoReflect.Descriptor instead.
func (*JournalRecord) Descriptor() ([]byte, []int) {
	return file_schema_journal_proto_rawDescGZIP(), []int{1}
}

func (x *JournalRecord) GetLeadershipTermId() int64 {
	if x != nil {
		return x.LeadershipTermId
	}
	return 0
}

func (x *JournalRecord) GetLogPosition() int64 {
	if x != nil {
		return x.LogPosition
	}
	return 0
}

func (x *JournalRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *JournalRecord) GetClusterSessionId() int64 {
	if x != nil {
		return x.ClusterSessionId
	}
	return 0
}

func (x *JournalRecord) GetCorrelationId() int64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *JournalRecord) GetLeaderMemberId() int32 {
	if x != nil {
		return x.LeaderMemberId
	}
	return 0
}

func (x *JournalRecord) GetServiceId() int32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *JournalRecord) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *JournalRecord) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *JournalRecord) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_schema_journal_proto protoreflect.FileDescriptor

const file_schema_journal_proto_rawDesc = "" +
	"\n" +
	"\x14schema/journal.proto\x12\x0ehiperf.journal\"\xb0\x01\n" +
	"\x05Entry\x12\"\n" +
	"\rentry_term_id\x18\x01 \x01(\x10R\ventryTermId\x12\x1f\n" +
	"\ventry_index\x18\x02 \x01(\x10R\n" +
	"entryIndex\x12'\n" +
	"\x0fentry_timestamp\x18\x03 \x01(\x10R\x0eentryTimestamp\x12\x1f\n" +
	"\vcommand_key\x18\x04 \x01(\x0fR\n" +
	"commandKey\x12\x18\n" +
	"\acommand\x18\x05 \x01(\fR\acommand\"\x82\x03\n" +
	"\rJournalRecord\x12,\n" +
	"\x12leadership_term_id\x18\x01 \x01(\x10R\x10leadershipTermId\x12!\n" +
	"\flog_position\x18\x02 \x01(\x10R\vlogPosition\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x10R\ttimestamp\x12,\n" +
	"\x12cluster_session_id\x18\x04 \x01(\x10R\x10clusterSessionId\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\x10R\rcorrelationId\x12(\n" +
	"\x10leader_member_id\x18\x06 \x01(\x0fR\x0eleaderMemberId\x12\x1d\n" +
	"\n" +
	"service_id\x18\a \x01(\x0fR\tserviceId\x12\x1d\n" +
	"\n" +
	"event_type\x18\b \x01(\rR\teventType\x12\x14\n" +
	"\x05flags\x18\t \x01(\rR\x05flags\x12/\n" +
	"\aentries\x18\n" +
	" \x03(\v2\x15.hiperf.journal.EntryR\aentriesBDZBgithub.com/peterknego/hi-perf-cmp/go/internal/serjournal/journalpbb\x06proto3"

var (
	file_schema_journal_proto_rawDescOnce sync.Once
	file_schema_journal_proto_rawDescData []byte
)

func file_schema_journal_proto_rawDescGZIP() []byte {
	file_schema_journal_proto_rawDescOnce.Do(func() {
		file_schema_journal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_journal_proto_rawDesc), len(file_schema_journal_proto_rawDesc)))
	})
	return file_schema_journal_proto_rawDescData
}

var file_schema_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schema_journal_proto_goTypes = []any{
	(*Entry)(nil),         // 0: hiperf.journal.Entry
	(*JournalRecord)(nil), // 1: hiperf.journal.JournalRecord
}
var file_schema_journal_proto_depIdxs = []int32{
	0, // 0: hiperf.journal.JournalRecord.entries:type_name -> hiperf.journal.Entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schema_journal_proto_init() }
func file_schema_journal_proto_init() {
	if File_schema_journal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_journal_proto_rawDesc), len(file_schema_journal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_journal_proto_goTypes,
		DependencyIndexes: file_schema_journal_proto_depIdxs,
		MessageInfos:      file_schema_journal_proto_msgTypes,
	}.Build()
	File_schema_journal_proto = out.File
	file_schema_journal_proto_goTypes = nil
	file_schema_journal_proto_depIdxs = nil
}
