// rpc-roundtrip flat payload + unary Roundtrip service (2026-07-17 spec).
// sfixed/fixed for the wide scalars (full-width values; matches the
// serialization protobuf cell's fixed-width choice); uint32 for byte-wide fields.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: schema/rpc_payload.proto

package payloadpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hop           uint32                 `protobuf:"fixed32,1,opt,name=hop,proto3" json:"hop,omitempty"`
	Seq           uint64                 `protobuf:"fixed64,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp     int64                  `protobuf:"fixed64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OrderId       uint64                 `protobuf:"fixed64,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Price         int64                  `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Qty           int64                  `protobuf:"fixed64,6,opt,name=qty,proto3" json:"qty,omitempty"`
	SymbolId      uint32                 `protobuf:"fixed32,7,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"`
	AccountId     uint64                 `protobuf:"fixed64,8,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	VenueId       uint32                 `protobuf:"varint,9,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Side          uint32                 `protobuf:"varint,10,opt,name=side,proto3" json:"side,omitempty"`
	Flags         uint32                 `protobuf:"varint,11,opt,name=flags,proto3" json:"flags,omitempty"`
	Signature     []byte                 `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	Context       []byte                 `protobuf:"bytes,13,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcPayload) Reset() {
	*x = RpcPayload{}
	mi := &file_schema_rpc_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcPayload) ProtoMessage() {}

func (x *RpcPayload) ProtoReflect() protoreflect.Message {
	mi := &file_schema_rpc_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcPayload.ProtoReflect.Descriptor instead.
func (*RpcPayload) Descriptor() ([]byte, []int) {
	return file_schema_rpc_payload_proto_rawDescGZIP(), []int{0}
}

func (x *RpcPayload) GetHop() uint32 {
	if x != nil {
		return x.Hop
	}
	return 0
}

func (x *RpcPayload) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RpcPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RpcPayload) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *RpcPayload) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RpcPayload) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *RpcPayload) GetSymbolId() uint32 {
	if x != nil {
		return x.SymbolId
	}
	return 0
}

func (x *RpcPayload) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RpcPayload) GetVenueId() uint32 {
	if x != nil {
		return x.VenueId
	}
	return 0
}

func (x *RpcPayload) GetSide() uint32 {
	if x != nil {
		return x.Side
	}
	return 0
}

func (x *RpcPayload) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *RpcPayload) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RpcPayload) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_schema_rpc_payload_proto protoreflect.FileDescriptor

const file_schema_rpc_payload_proto_rawDesc = "" +
	"\n" +
	"\x18schema/rpc_payload.proto\x12\n" +
	"hiperf.rpc\"\xca\x02\n" +
	"\n" +
	"RpcPayload\x12\x10\n" +
	"\x03hop\x18\x01 \x01(\aR\x03hop\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x06R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x10R\ttimestamp\x12\x19\n" +
	"\border_id\x18\x04 \x01(\x06R\aorderId\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x10R\x05price\x12\x10\n" +
	"\x03qty\x18\x06 \x01(\x10R\x03qty\x12\x1b\n" +
	"\tsymbol_id\x18\a \x01(\aR\bsymbolId\x12\x1d\n" +
	"\n" +
	"account_id\x18\b \x01(\x06R\taccountId\x12\x19\n" +
	"\bvenue_id\x18\t \x01(\rR\avenueId\x12\x12\n" +
	"\x04side\x18\n" +
	" \x01(\rR\x04side\x12\x14\n" +
	"\x05flags\x18\v \x01(\rR\x05flags\x12\x1c\n" +
	"\tsignature\x18\f \x01(\fR\tsignature\x12\x18\n" +
	"\acontext\x18\r \x01(\fR\acontext2K\n" +
	"\fRpcRoundtrip\x12;\n" +
	"\tRoundtrip\x12\x16.hiperf.rpc.RpcPayload\x1a\x16.hiperf.rpc.RpcPayloadBDZBgithub.com/peterknego/hi-perf-cmp/go/internal/rpcpayload/payloadpbb\x06proto3"

var (
	file_schema_rpc_payload_proto_rawDescOnce sync.Once
	file_schema_rpc_payload_proto_rawDescData []byte
)

func file_schema_rpc_payload_proto_rawDescGZIP() []byte {
	file_schema_rpc_payload_proto_rawDescOnce.Do(func() {
		file_schema_rpc_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_rpc_payload_proto_rawDesc), len(file_schema_rpc_payload_proto_rawDesc)))
	})
	return file_schema_rpc_payload_proto_rawDescData
}

var file_schema_rpc_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_rpc_payload_proto_goTypes = []any{
	(*RpcPayload)(nil), // 0: hiperf.rpc.RpcPayload
}
var file_schema_rpc_payload_proto_depIdxs = []int32{
	0, // 0: hiperf.rpc.RpcRoundtrip.Roundtrip:input_type -> hiperf.rpc.RpcPayload
	0, // 1: hiperf.rpc.RpcRoundtrip.Roundtrip:output_type -> hiperf.rpc.RpcPayload
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_rpc_payload_proto_init() }
func file_schema_rpc_payload_proto_init() {
	if File_schema_rpc_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_rpc_payload_proto_rawDesc), len(file_schema_rpc_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_rpc_payload_proto_goTypes,
		DependencyIndexes: file_schema_rpc_payload_proto_depIdxs,
		MessageInfos:      file_schema_rpc_payload_proto_msgTypes,
	}.Build()
	File_schema_rpc_payload_proto = out.File
	file_schema_rpc_payload_proto_goTypes = nil
	file_schema_rpc_payload_proto_depIdxs = nil
}
