// rpc-roundtrip flat payload + unary Roundtrip service (2026-07-17 spec).
// sfixed/fixed for the wide scalars (full-width values; matches the
// serialization protobuf cell's fixed-width choice); uint32 for byte-wide fields.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: schema/rpc_payload.proto

package payloadpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcRoundtrip_Roundtrip_FullMethodName = "/hiperf.rpc.RpcRoundtrip/Roundtrip"
)

// RpcRoundtripClient is the client API for RpcRoundtrip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcRoundtripClient interface {
	Roundtrip(ctx context.Context, in *RpcPayload, opts ...grpc.CallOption) (*RpcPayload, error)
}

type rpcRoundtripClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcRoundtripClient(cc grpc.ClientConnInterface) RpcRoundtripClient {
	return &rpcRoundtripClient{cc}
}

func (c *rpcRoundtripClient) Roundtrip(ctx context.Context, in *RpcPayload, opts ...grpc.CallOption) (*RpcPayload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcPayload)
	err := c.cc.Invoke(ctx, RpcRoundtrip_Roundtrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcRoundtripServer is the server API for RpcRoundtrip service.
// All implementations must embed UnimplementedRpcRoundtripServer
// for forward compatibility.
type RpcRoundtripServer interface {
	Roundtrip(context.Context, *RpcPayload) (*RpcPayload, error)
	mustEmbedUnimplementedRpcRoundtripServer()
}

// UnimplementedRpcRoundtripServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcRoundtripServer struct{}

func (UnimplementedRpcRoundtripServer) Roundtrip(context.Context, *RpcPayload) (*RpcPayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Roundtrip not implemented")
}
func (UnimplementedRpcRoundtripServer) mustEmbedUnimplementedRpcRoundtripServer() {}
func (UnimplementedRpcRoundtripServer) testEmbeddedByValue()                      {}

// UnsafeRpcRoundtripServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcRoundtripServer will
// result in compilation errors.
type UnsafeRpcRoundtripServer interface {
	mustEmbedUnimplementedRpcRoundtripServer()
}

func RegisterRpcRoundtripServer(s grpc.ServiceRegistrar, srv RpcRoundtripServer) {
	// If the following call pancis, it indicates UnimplementedRpcRoundtripServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcRoundtrip_ServiceDesc, srv)
}

func _RpcRoundtrip_Roundtrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcRoundtripServer).Roundtrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcRoundtrip_Roundtrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcRoundtripServer).Roundtrip(ctx, req.(*RpcPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcRoundtrip_ServiceDesc is the grpc.ServiceDesc for RpcRoundtrip service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcRoundtrip_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hiperf.rpc.RpcRoundtrip",
	HandlerType: (*RpcRoundtripServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Roundtrip",
			Handler:    _RpcRoundtrip_Roundtrip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema/rpc_payload.proto",
}
