// Code generated by bebopc-go; DO NOT EDIT.

package payloadbop

import (
	"github.com/200sc/bebop"
	"github.com/200sc/bebop/iohelp"
	"io"
)

var _ bebop.Record = &RpcPayload{}

// rpc-roundtrip flat payload (see the 2026-07-17 design spec). `flags` is a
// reserved bebop keyword, so the field is recordFlags.
type RpcPayload struct {
	Hop         uint32
	Seq         uint64
	Timestamp   int64
	OrderId     uint64
	Price       int64
	Qty         int64
	SymbolId    uint32
	AccountId   uint64
	VenueId     uint16
	Side        byte
	RecordFlags byte
	Signature   []byte
	Context     []byte
}

func (bbp RpcPayload) MarshalBebopTo(buf []byte) int {
	at := 0
	iohelp.WriteUint32Bytes(buf[at:], bbp.Hop)
	at += 4
	iohelp.WriteUint64Bytes(buf[at:], bbp.Seq)
	at += 8
	iohelp.WriteInt64Bytes(buf[at:], bbp.Timestamp)
	at += 8
	iohelp.WriteUint64Bytes(buf[at:], bbp.OrderId)
	at += 8
	iohelp.WriteInt64Bytes(buf[at:], bbp.Price)
	at += 8
	iohelp.WriteInt64Bytes(buf[at:], bbp.Qty)
	at += 8
	iohelp.WriteUint32Bytes(buf[at:], bbp.SymbolId)
	at += 4
	iohelp.WriteUint64Bytes(buf[at:], bbp.AccountId)
	at += 8
	iohelp.WriteUint16Bytes(buf[at:], bbp.VenueId)
	at += 2
	iohelp.WriteByteBytes(buf[at:], bbp.Side)
	at += 1
	iohelp.WriteByteBytes(buf[at:], bbp.RecordFlags)
	at += 1
	iohelp.WriteUint32Bytes(buf[at:], uint32(len(bbp.Signature)))
	at += 4
	copy(buf[at:at+len(bbp.Signature)], bbp.Signature)
	at += len(bbp.Signature)
	iohelp.WriteUint32Bytes(buf[at:], uint32(len(bbp.Context)))
	at += 4
	copy(buf[at:at+len(bbp.Context)], bbp.Context)
	at += len(bbp.Context)
	return at
}

func (bbp *RpcPayload) UnmarshalBebop(buf []byte) (err error) {
	at := 0
	if len(buf[at:]) < 4 {
		return io.ErrUnexpectedEOF
	}
	bbp.Hop = iohelp.ReadUint32Bytes(buf[at:])
	at += 4
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.Seq = iohelp.ReadUint64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.Timestamp = iohelp.ReadInt64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.OrderId = iohelp.ReadUint64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.Price = iohelp.ReadInt64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.Qty = iohelp.ReadInt64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 4 {
		return io.ErrUnexpectedEOF
	}
	bbp.SymbolId = iohelp.ReadUint32Bytes(buf[at:])
	at += 4
	if len(buf[at:]) < 8 {
		return io.ErrUnexpectedEOF
	}
	bbp.AccountId = iohelp.ReadUint64Bytes(buf[at:])
	at += 8
	if len(buf[at:]) < 2 {
		return io.ErrUnexpectedEOF
	}
	bbp.VenueId = iohelp.ReadUint16Bytes(buf[at:])
	at += 2
	if len(buf[at:]) < 1 {
		return io.ErrUnexpectedEOF
	}
	bbp.Side = iohelp.ReadByteBytes(buf[at:])
	at += 1
	if len(buf[at:]) < 1 {
		return io.ErrUnexpectedEOF
	}
	bbp.RecordFlags = iohelp.ReadByteBytes(buf[at:])
	at += 1
	if len(buf[at:]) < 4 {
		return io.ErrUnexpectedEOF
	}
	bbp.Signature = make([]byte, iohelp.ReadUint32Bytes(buf[at:]))
	at += 4
	if len(buf[at:]) < len(bbp.Signature)*1 {
		return io.ErrUnexpectedEOF
	}
	copy(bbp.Signature, buf[at:at+len(bbp.Signature)])
	at += len(bbp.Signature)
	if len(buf[at:]) < 4 {
		return io.ErrUnexpectedEOF
	}
	bbp.Context = make([]byte, iohelp.ReadUint32Bytes(buf[at:]))
	at += 4
	if len(buf[at:]) < len(bbp.Context)*1 {
		return io.ErrUnexpectedEOF
	}
	copy(bbp.Context, buf[at:at+len(bbp.Context)])
	at += len(bbp.Context)
	return nil
}

func (bbp RpcPayload) EncodeBebop(iow io.Writer) (err error) {
	w := iohelp.NewErrorWriter(iow)
	iohelp.WriteUint32(w, bbp.Hop)
	iohelp.WriteUint64(w, bbp.Seq)
	iohelp.WriteInt64(w, bbp.Timestamp)
	iohelp.WriteUint64(w, bbp.OrderId)
	iohelp.WriteInt64(w, bbp.Price)
	iohelp.WriteInt64(w, bbp.Qty)
	iohelp.WriteUint32(w, bbp.SymbolId)
	iohelp.WriteUint64(w, bbp.AccountId)
	iohelp.WriteUint16(w, bbp.VenueId)
	iohelp.WriteByte(w, bbp.Side)
	iohelp.WriteByte(w, bbp.RecordFlags)
	iohelp.WriteUint32(w, uint32(len(bbp.Signature)))
	w.Write(bbp.Signature)
	iohelp.WriteUint32(w, uint32(len(bbp.Context)))
	w.Write(bbp.Context)
	return w.Err
}

func (bbp *RpcPayload) DecodeBebop(ior io.Reader) (err error) {
	r := iohelp.NewErrorReader(ior)
	bbp.Hop = iohelp.ReadUint32(r)
	bbp.Seq = iohelp.ReadUint64(r)
	bbp.Timestamp = iohelp.ReadInt64(r)
	bbp.OrderId = iohelp.ReadUint64(r)
	bbp.Price = iohelp.ReadInt64(r)
	bbp.Qty = iohelp.ReadInt64(r)
	bbp.SymbolId = iohelp.ReadUint32(r)
	bbp.AccountId = iohelp.ReadUint64(r)
	bbp.VenueId = iohelp.ReadUint16(r)
	bbp.Side = iohelp.ReadByte(r)
	bbp.RecordFlags = iohelp.ReadByte(r)
	bbp.Signature = make([]byte, iohelp.ReadUint32(r))
	r.Read(bbp.Signature)
	bbp.Context = make([]byte, iohelp.ReadUint32(r))
	r.Read(bbp.Context)
	return r.Err
}

func (bbp RpcPayload) Size() int {
	bodyLen := 0
	bodyLen += 4
	bodyLen += 8
	bodyLen += 8
	bodyLen += 8
	bodyLen += 8
	bodyLen += 8
	bodyLen += 4
	bodyLen += 8
	bodyLen += 2
	bodyLen += 1
	bodyLen += 1
	bodyLen += 4
	bodyLen += len(bbp.Signature) * 1
	bodyLen += 4
	bodyLen += len(bbp.Context) * 1
	return bodyLen
}

func (bbp RpcPayload) MarshalBebop() []byte {
	buf := make([]byte, bbp.Size())
	bbp.MarshalBebopTo(buf)
	return buf
}

func MakeRpcPayload(r *iohelp.ErrorReader) (RpcPayload, error) {
	v := RpcPayload{}
	err := v.DecodeBebop(r)
	return v, err
}

func MakeRpcPayloadFromBytes(buf []byte) (RpcPayload, error) {
	v := RpcPayload{}
	err := v.UnmarshalBebop(buf)
	return v, err
}
