/* Generated SBE (Simple Binary Encoding) message codec */
// Code generated by SBE. DO NOT EDIT.

package journalsbe

import (
	"errors"
	"fmt"
)

type EventType uint8

const (
	EventType_APPEND     EventType = EventType(uint8(0))
	EventType_SNAPSHOT   EventType = EventType(uint8(1))
	EventType_NULL_VALUE EventType = EventType(uint8(255))
)

var EventTypeLookupErr = errors.New("unknown value for enum EventType [E103]")

func LookupEventType(value uint8) (EventType, error) {
	switch value {
	case uint8(0):
		return EventType_APPEND, nil
	case uint8(1):
		return EventType_SNAPSHOT, nil
	case uint8(255):
		return EventType_NULL_VALUE, nil
	}

	return 0, EventTypeLookupErr
}

func (value EventType) String() string {
	switch value {
	case EventType_APPEND:
		return "APPEND"
	case EventType_SNAPSHOT:
		return "SNAPSHOT"
	case EventType_NULL_VALUE:
		return "NULL_VALUE"
	}

	panic(fmt.Sprintf("unknown value for enum EventType [E103]: %d", value))
}
