/* Generated SBE (Simple Binary Encoding) message codec */
// Code generated by SBE. DO NOT EDIT.

package journalsbe

import (
	"fmt"
	"strings"
)

type JournalRecord struct {
	buffer            []byte
	bufferLength      uint64
	offset            uint64
	position          uint64
	actingBlockLength uint64
	actingVersion     uint64
	_Entries          JournalRecordEntries
}

func (m *JournalRecord) sbePositionPtr() *uint64 {
	return &m.position
}

const (
	JournalRecordSbeBlockLength     uint16 = uint16(50)
	JournalRecordSbeTemplateID      uint16 = uint16(1)
	JournalRecordSbeSchemaID        uint16 = uint16(7)
	JournalRecordSbeSchemaVersion   uint16 = uint16(1)
	JournalRecordSbeSemanticVersion string = ""
)

func (m *JournalRecord) SbeBlockLength() uint16 {
	return uint16(50)
}

func (m *JournalRecord) SbeBlockAndHeaderLength() uint64 {
	return MessageHeaderEncodedLength + uint64(m.SbeBlockLength())
}

func (m *JournalRecord) SbeTemplateId() uint16 {
	return uint16(1)
}

func (m *JournalRecord) SbeSchemaId() uint16 {
	return uint16(7)
}

func (m *JournalRecord) SbeSchemaVersion() uint16 {
	return uint16(1)
}

func (m *JournalRecord) SbeSemanticVersion() string {
	return ""
}

func (m *JournalRecord) SbeSemanticType() string {
	return ""
}

func (m *JournalRecord) Offset() uint64 {
	return m.offset
}

func (m *JournalRecord) Wrap(
	buffer []byte,
	offset uint64,
	bufferLength uint64,
	actingBlockLength uint64,
	actingVersion uint64) *JournalRecord {
	m.buffer = buffer
	m.bufferLength = bufferLength
	m.offset = offset
	m.position = m.SbeCheckPosition(offset + actingBlockLength)
	m.actingBlockLength = actingBlockLength
	m.actingVersion = actingVersion
	return m
}

func (m *JournalRecord) WrapForEncode(buffer []byte, offset uint64, bufferLength uint64) *JournalRecord {
	return m.Wrap(buffer, offset, bufferLength,
		uint64(m.SbeBlockLength()), uint64(m.SbeSchemaVersion()))
}

func (m *JournalRecord) WrapAndApplyHeader(buffer []byte, offset uint64, bufferLength uint64) *JournalRecord {
	var hdr MessageHeader
	hdr.Wrap(buffer, offset, uint64(m.SbeSchemaVersion()), bufferLength)

	hdr.SetBlockLength(m.SbeBlockLength()).
		SetTemplateId(m.SbeTemplateId()).
		SetSchemaId(m.SbeSchemaId()).
		SetVersion(m.SbeSchemaVersion())

	return m.Wrap(
		buffer,
		offset+hdr.EncodedLength(),
		bufferLength,
		uint64(m.SbeBlockLength()),
		uint64(m.SbeSchemaVersion()))
}

func (m *JournalRecord) WrapForDecode(
	buffer []byte,
	offset uint64,
	actingBlockLength uint64,
	actingVersion uint64,
	bufferLength uint64) *JournalRecord {
	return m.Wrap(
		buffer,
		offset,
		bufferLength,
		actingBlockLength,
		actingVersion)
}

func (m *JournalRecord) sbeRewind() *JournalRecord {
	return m.WrapForDecode(m.buffer, m.offset, m.actingBlockLength, m.actingVersion, m.bufferLength)
}

func (m *JournalRecord) SbePosition() uint64 {
	return m.position
}

func (m *JournalRecord) SbeCheckPosition(position uint64) uint64 {
	if !SbeNoBoundsCheck && (position > m.bufferLength) {
		panic("buffer too short [E100]")
	}
	return position
}

func (m *JournalRecord) SetSbePosition(position uint64) {
	m.position = m.SbeCheckPosition(position)
}

func (m *JournalRecord) EncodedLength() uint64 {
	return m.SbePosition() - m.offset
}

func (m *JournalRecord) DecodeLength() uint64 {
	var skipper JournalRecord
	skipper.WrapForDecode(m.buffer, m.offset, uint64(m.SbeBlockLength()),
		uint64(m.ActingVersion()), m.bufferLength)
	skipper.Skip()
	return skipper.EncodedLength()
}

func (m *JournalRecord) Buffer() []byte {
	return m.buffer
}

func (m *JournalRecord) BufferLength() uint64 {
	return m.bufferLength
}

func (m *JournalRecord) ActingVersion() uint64 {
	return m.actingVersion
}

func (m *JournalRecord) LeadershipTermIdMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecord) LeadershipTermIdId() int {
	return 1
}

func (m *JournalRecord) LeadershipTermIdSinceVersion() uint64 {
	return 0
}

func (m *JournalRecord) LeadershipTermIdInActingVersion() bool {
	return true
}

func (m *JournalRecord) LeadershipTermIdEncodingOffset() uint {
	return 0
}

func (m *JournalRecord) LeadershipTermIdNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *JournalRecord) LeadershipTermIdMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *JournalRecord) LeadershipTermIdMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *JournalRecord) LeadershipTermIdEncodingLength() int {
	return 8
}

func (m *JournalRecord) LeadershipTermId() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 0):])
}

func (m *JournalRecord) SetLeadershipTermId(value int64) *JournalRecord {
	PutInt64LittleEndian(m.buffer[(m.offset+0):], value)
	return m
}

func (m *JournalRecord) LogPositionMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecord) LogPositionId() int {
	return 2
}

func (m *JournalRecord) LogPositionSinceVersion() uint64 {
	return 0
}

func (m *JournalRecord) LogPositionInActingVersion() bool {
	return true
}

func (m *JournalRecord) LogPositionEncodingOffset() uint {
	return 8
}

func (m *JournalRecord) LogPositionNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *JournalRecord) LogPositionMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *JournalRecord) LogPositionMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *JournalRecord) LogPositionEncodingLength() int {
	return 8
}

func (m *JournalRecord) LogPosition() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 8):])
}

func (m *JournalRecord) SetLogPosition(value int64) *JournalRecord {
	PutInt64LittleEndian(m.buffer[(m.offset+8):], value)
	return m
}

func (m *JournalRecord) TimestampMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecord) TimestampId() int {
	return 3
}

func (m *JournalRecord) TimestampSinceVersion() uint64 {
	return 0
}

func (m *JournalRecord) TimestampInActingVersion() bool {
	return true
}

func (m *JournalRecord) TimestampEncodingOffset() uint {
	return 16
}

func (m *JournalRecord) TimestampNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *JournalRecord) TimestampMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *JournalRecord) TimestampMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *JournalRecord) TimestampEncodingLength() int {
	return 8
}

func (m *JournalRecord) Timestamp() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 16):])
}

func (m *JournalRecord) SetTimestamp(value int64) *JournalRecord {
	PutInt64LittleEndian(m.buffer[(m.offset+16):], value)
	return m
}

func (m *JournalRecord) ClusterSessionIdMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecord) ClusterSessionIdId() int {
	return 4
}

func (m *JournalRecord) ClusterSessionIdSinceVersion() uint64 {
	return 0
}

func (m *JournalRecord) ClusterSessionIdInActingVersion() bool {
	return true
}

func (m *JournalRecord) ClusterSessionIdEncodingOffset() uint {
	return 24
}

func (m *JournalRecord) ClusterSessionIdNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *JournalRecord) ClusterSessionIdMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *JournalRecord) ClusterSessionIdMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *JournalRecord) ClusterSessionIdEncodingLength() int {
	return 8
}

func (m *JournalRecord) ClusterSessionId() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 24):])
}

func (m *JournalRecord) SetClusterSessionId(value int64) *JournalRecord {
	PutInt64LittleEndian(m.buffer[(m.offset+24):], value)
	return m
}

func (m *JournalRecord) CorrelationIdMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecord) CorrelationIdId() int {
	return 5
}

func (m *JournalRecord) CorrelationIdSinceVersion() uint64 {
	return 0
}

func (m *JournalRecord) CorrelationIdInActingVersion() bool {
	return true
}

func (m *JournalRecord) CorrelationIdEncodingOffset() uint {
	return 32
}

func (m *JournalRecord) CorrelationIdNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *JournalRecord) CorrelationIdMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *JournalRecord) CorrelationIdMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *JournalRecord) CorrelationIdEncodingLength() int {
	return 8
}

func (m *JournalRecord) CorrelationId() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 32):])
}

func (m *JournalRecord) SetCorrelationId(value int64) *JournalRecord {
	PutInt64LittleEndian(m.buffer[(m.offset+32):], value)
	return m
}

func (m *JournalRecord) LeaderMemberIdMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecord) LeaderMemberIdId() int {
	return 6
}

func (m *JournalRecord) LeaderMemberIdSinceVersion() uint64 {
	return 0
}

func (m *JournalRecord) LeaderMemberIdInActingVersion() bool {
	return true
}

func (m *JournalRecord) LeaderMemberIdEncodingOffset() uint {
	return 40
}

func (m *JournalRecord) LeaderMemberIdNullValue() int32 {
	return SbeNullValueInt32()
}

func (m *JournalRecord) LeaderMemberIdMinValue() int32 {
	return int32(-2147483647)
}

func (m *JournalRecord) LeaderMemberIdMaxValue() int32 {
	return int32(2147483647)
}

func (m *JournalRecord) LeaderMemberIdEncodingLength() int {
	return 4
}

func (m *JournalRecord) LeaderMemberId() int32 {
	return Int32LittleEndian(m.buffer[(m.offset + 40):])
}

func (m *JournalRecord) SetLeaderMemberId(value int32) *JournalRecord {
	PutInt32LittleEndian(m.buffer[(m.offset+40):], value)
	return m
}

func (m *JournalRecord) ServiceIdMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecord) ServiceIdId() int {
	return 7
}

func (m *JournalRecord) ServiceIdSinceVersion() uint64 {
	return 0
}

func (m *JournalRecord) ServiceIdInActingVersion() bool {
	return true
}

func (m *JournalRecord) ServiceIdEncodingOffset() uint {
	return 44
}

func (m *JournalRecord) ServiceIdNullValue() int32 {
	return SbeNullValueInt32()
}

func (m *JournalRecord) ServiceIdMinValue() int32 {
	return int32(-2147483647)
}

func (m *JournalRecord) ServiceIdMaxValue() int32 {
	return int32(2147483647)
}

func (m *JournalRecord) ServiceIdEncodingLength() int {
	return 4
}

func (m *JournalRecord) ServiceId() int32 {
	return Int32LittleEndian(m.buffer[(m.offset + 44):])
}

func (m *JournalRecord) SetServiceId(value int32) *JournalRecord {
	PutInt32LittleEndian(m.buffer[(m.offset+44):], value)
	return m
}

func (m *JournalRecord) EventTypeMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecord) EventTypeId() int {
	return 8
}

func (m *JournalRecord) EventTypeSinceVersion() uint64 {
	return 0
}

func (m *JournalRecord) EventTypeInActingVersion() bool {
	return true
}

func (m *JournalRecord) EventTypeEncodingOffset() uint {
	return 48
}

func (m *JournalRecord) EventTypeEncodingLength() int {
	return 1
}

func (m *JournalRecord) EventTypeRaw() uint8 {
	return Uint8LittleEndian(m.buffer[(m.offset + 48):])
}

func (m *JournalRecord) EventType() EventType {
	return EventType(Uint8LittleEndian(m.buffer[(m.offset + 48):]))
}

func (m *JournalRecord) SetEventType(value EventType) *JournalRecord {
	val := uint8(value)
	PutUint8LittleEndian(m.buffer[(m.offset+48):], val)
	return m
}

func (m *JournalRecord) FlagsMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecord) FlagsId() int {
	return 9
}

func (m *JournalRecord) FlagsSinceVersion() uint64 {
	return 0
}

func (m *JournalRecord) FlagsInActingVersion() bool {
	return true
}

func (m *JournalRecord) FlagsEncodingOffset() uint {
	return 49
}

func (m *JournalRecord) FlagsNullValue() uint8 {
	return SbeNullValueUint8()
}

func (m *JournalRecord) FlagsMinValue() uint8 {
	return uint8(0)
}

func (m *JournalRecord) FlagsMaxValue() uint8 {
	return uint8(254)
}

func (m *JournalRecord) FlagsEncodingLength() int {
	return 1
}

func (m *JournalRecord) Flags() uint8 {
	return Uint8LittleEndian(m.buffer[(m.offset + 49):])
}

func (m *JournalRecord) SetFlags(value uint8) *JournalRecord {
	PutUint8LittleEndian(m.buffer[(m.offset+49):], value)
	return m
}

type JournalRecordEntries struct {
	buffer          []byte
	bufferLength    uint64
	initialPosition uint64
	positionPtr     *uint64
	blockLength     uint64
	count           uint64
	index           uint64
	offset          uint64
	actingVersion   uint64
}

func (g *JournalRecordEntries) sbePositionPtr() *uint64 {
	return g.positionPtr
}

func (g *JournalRecordEntries) WrapForDecode(
	buffer []byte,
	pos *uint64,
	actingVersion uint64,
	bufferLength uint64) {
	dimensions := GroupSizeEncoding{}
	dimensions.Wrap(buffer, *pos, actingVersion, bufferLength)
	g.buffer = buffer
	g.bufferLength = bufferLength
	g.blockLength = uint64(dimensions.BlockLength())
	g.count = uint64(dimensions.NumInGroup())
	g.index = 0
	g.actingVersion = actingVersion
	g.initialPosition = *pos
	g.positionPtr = pos
	*g.positionPtr = *g.positionPtr + 4
}

func (g *JournalRecordEntries) WrapForEncode(
	buffer []byte,
	count uint16,
	pos *uint64,
	actingVersion uint64,
	bufferLength uint64) {
	if count > 65534 {
		panic("count outside of allowed range [E110]")
	}
	g.buffer = buffer
	g.bufferLength = bufferLength
	dimensions := GroupSizeEncoding{}
	dimensions.Wrap(buffer, *pos, actingVersion, bufferLength)
	dimensions.SetBlockLength(45)
	dimensions.SetNumInGroup(count)
	g.index = 0
	g.count = uint64(count)
	g.blockLength = 45
	g.actingVersion = actingVersion
	g.initialPosition = *pos
	g.positionPtr = pos
	*g.positionPtr = *g.positionPtr + 4
}

func (g *JournalRecordEntries) SbeHeaderSize() uint64 {
	return 4
}

func (g *JournalRecordEntries) SbeBlockLength() uint64 {
	return 45
}

func (g *JournalRecordEntries) SbePosition() uint64 {
	return *g.positionPtr
}

func (g *JournalRecordEntries) SbeCheckPosition(position uint64) uint64 {
	if position > g.bufferLength {
		panic("buffer too short [E100]")
	}
	return position
}

func (g *JournalRecordEntries) SetSbePosition(position uint64) {
	*g.positionPtr = g.SbeCheckPosition(position)
}

func (g *JournalRecordEntries) Count() uint64 {
	return g.count
}

func (g *JournalRecordEntries) HasNext() bool {
	return g.index < g.count
}

func (g *JournalRecordEntries) Next() *JournalRecordEntries {
	if g.index >= g.count {
		panic("index >= count [E108]")
	}
	g.offset = *g.positionPtr
	if g.offset+g.blockLength > g.bufferLength {
		panic("buffer too short for next group index [E108]")
	}
	*g.positionPtr = g.offset + g.blockLength
	g.index++

	return g
}

func (g *JournalRecordEntries) ResetCountToIndex() uint64 {
	g.count = g.index
	dimensions := GroupSizeEncoding{}
	dimensions.Wrap(g.buffer, g.initialPosition, g.actingVersion, g.bufferLength)
	dimensions.SetNumInGroup(uint16(g.count))
	return g.count
}

func (g *JournalRecordEntries) ForEach(fn func(group *JournalRecordEntries)) {
	for g.HasNext() {
		g.Next()
		fn(g)
	}
}

func (m *JournalRecordEntries) EntryTermIdMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecordEntries) EntryTermIdId() int {
	return 11
}

func (m *JournalRecordEntries) EntryTermIdSinceVersion() uint64 {
	return 0
}

func (m *JournalRecordEntries) EntryTermIdInActingVersion() bool {
	return true
}

func (m *JournalRecordEntries) EntryTermIdEncodingOffset() uint {
	return 0
}

func (m *JournalRecordEntries) EntryTermIdNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *JournalRecordEntries) EntryTermIdMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *JournalRecordEntries) EntryTermIdMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *JournalRecordEntries) EntryTermIdEncodingLength() int {
	return 8
}

func (m *JournalRecordEntries) EntryTermId() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 0):])
}

func (m *JournalRecordEntries) SetEntryTermId(value int64) *JournalRecordEntries {
	PutInt64LittleEndian(m.buffer[(m.offset+0):], value)
	return m
}

func (m *JournalRecordEntries) EntryIndexMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecordEntries) EntryIndexId() int {
	return 12
}

func (m *JournalRecordEntries) EntryIndexSinceVersion() uint64 {
	return 0
}

func (m *JournalRecordEntries) EntryIndexInActingVersion() bool {
	return true
}

func (m *JournalRecordEntries) EntryIndexEncodingOffset() uint {
	return 8
}

func (m *JournalRecordEntries) EntryIndexNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *JournalRecordEntries) EntryIndexMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *JournalRecordEntries) EntryIndexMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *JournalRecordEntries) EntryIndexEncodingLength() int {
	return 8
}

func (m *JournalRecordEntries) EntryIndex() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 8):])
}

func (m *JournalRecordEntries) SetEntryIndex(value int64) *JournalRecordEntries {
	PutInt64LittleEndian(m.buffer[(m.offset+8):], value)
	return m
}

func (m *JournalRecordEntries) EntryTimestampMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecordEntries) EntryTimestampId() int {
	return 13
}

func (m *JournalRecordEntries) EntryTimestampSinceVersion() uint64 {
	return 0
}

func (m *JournalRecordEntries) EntryTimestampInActingVersion() bool {
	return true
}

func (m *JournalRecordEntries) EntryTimestampEncodingOffset() uint {
	return 16
}

func (m *JournalRecordEntries) EntryTimestampNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *JournalRecordEntries) EntryTimestampMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *JournalRecordEntries) EntryTimestampMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *JournalRecordEntries) EntryTimestampEncodingLength() int {
	return 8
}

func (m *JournalRecordEntries) EntryTimestamp() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 16):])
}

func (m *JournalRecordEntries) SetEntryTimestamp(value int64) *JournalRecordEntries {
	PutInt64LittleEndian(m.buffer[(m.offset+16):], value)
	return m
}

func (m *JournalRecordEntries) CommandKeyMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecordEntries) CommandKeyId() int {
	return 14
}

func (m *JournalRecordEntries) CommandKeySinceVersion() uint64 {
	return 0
}

func (m *JournalRecordEntries) CommandKeyInActingVersion() bool {
	return true
}

func (m *JournalRecordEntries) CommandKeyEncodingOffset() uint {
	return 24
}

func (m *JournalRecordEntries) CommandKeyNullValue() int32 {
	return SbeNullValueInt32()
}

func (m *JournalRecordEntries) CommandKeyMinValue() int32 {
	return int32(-2147483647)
}

func (m *JournalRecordEntries) CommandKeyMaxValue() int32 {
	return int32(2147483647)
}

func (m *JournalRecordEntries) CommandKeyEncodingLength() int {
	return 4
}

func (m *JournalRecordEntries) CommandKey() int32 {
	return Int32LittleEndian(m.buffer[(m.offset + 24):])
}

func (m *JournalRecordEntries) SetCommandKey(value int32) *JournalRecordEntries {
	PutInt32LittleEndian(m.buffer[(m.offset+24):], value)
	return m
}

func (m *JournalRecordEntries) CmdQtyMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecordEntries) CmdQtyId() int {
	return 15
}

func (m *JournalRecordEntries) CmdQtySinceVersion() uint64 {
	return 0
}

func (m *JournalRecordEntries) CmdQtyInActingVersion() bool {
	return true
}

func (m *JournalRecordEntries) CmdQtyEncodingOffset() uint {
	return 28
}

func (m *JournalRecordEntries) CmdQtyNullValue() int64 {
	return SbeNullValueInt64()
}

func (m *JournalRecordEntries) CmdQtyMinValue() int64 {
	return int64(-9223372036854775807)
}

func (m *JournalRecordEntries) CmdQtyMaxValue() int64 {
	return int64(9223372036854775807)
}

func (m *JournalRecordEntries) CmdQtyEncodingLength() int {
	return 8
}

func (m *JournalRecordEntries) CmdQty() int64 {
	return Int64LittleEndian(m.buffer[(m.offset + 28):])
}

func (m *JournalRecordEntries) SetCmdQty(value int64) *JournalRecordEntries {
	PutInt64LittleEndian(m.buffer[(m.offset+28):], value)
	return m
}

func (m *JournalRecordEntries) CmdPriceMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecordEntries) CmdPriceId() int {
	return 16
}

func (m *JournalRecordEntries) CmdPriceSinceVersion() uint64 {
	return 0
}

func (m *JournalRecordEntries) CmdPriceInActingVersion() bool {
	return true
}

func (m *JournalRecordEntries) CmdPriceEncodingOffset() uint {
	return 36
}

func (m *JournalRecordEntries) CmdPriceNullValue() float64 {
	return SbeNullValueDouble()
}

func (m *JournalRecordEntries) CmdPriceMinValue() float64 {
	return -1.7976931348623157e308
}

func (m *JournalRecordEntries) CmdPriceMaxValue() float64 {
	return 1.7976931348623157e308
}

func (m *JournalRecordEntries) CmdPriceEncodingLength() int {
	return 8
}

func (m *JournalRecordEntries) CmdPrice() float64 {
	return DoubleLittleEndian(m.buffer[(m.offset + 36):])
}

func (m *JournalRecordEntries) SetCmdPrice(value float64) *JournalRecordEntries {
	PutDoubleLittleEndian(m.buffer[(m.offset+36):], value)
	return m
}

func (m *JournalRecordEntries) CmdFlagMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecordEntries) CmdFlagId() int {
	return 17
}

func (m *JournalRecordEntries) CmdFlagSinceVersion() uint64 {
	return 0
}

func (m *JournalRecordEntries) CmdFlagInActingVersion() bool {
	return true
}

func (m *JournalRecordEntries) CmdFlagEncodingOffset() uint {
	return 44
}

func (m *JournalRecordEntries) CmdFlagNullValue() uint8 {
	return SbeNullValueUint8()
}

func (m *JournalRecordEntries) CmdFlagMinValue() uint8 {
	return uint8(0)
}

func (m *JournalRecordEntries) CmdFlagMaxValue() uint8 {
	return uint8(254)
}

func (m *JournalRecordEntries) CmdFlagEncodingLength() int {
	return 1
}

func (m *JournalRecordEntries) CmdFlag() uint8 {
	return Uint8LittleEndian(m.buffer[(m.offset + 44):])
}

func (m *JournalRecordEntries) SetCmdFlag(value uint8) *JournalRecordEntries {
	PutUint8LittleEndian(m.buffer[(m.offset+44):], value)
	return m
}

func (m *JournalRecordEntries) CmdTextMetaAttribute(metaAttribute string) string {
	switch metaAttribute {
	case "PRESENCE":
		return "required"
	default:
		return ""
	}
}

func (m *JournalRecordEntries) CmdTextCharacterEncoding() string {
	return "null"
}

func (m *JournalRecordEntries) CmdTextSinceVersion() uint64 {
	return 0
}

func (m *JournalRecordEntries) CmdTextInActingVersion() bool {
	return true
}

func (m *JournalRecordEntries) CmdTextId() uint16 {
	return 18
}

func (m *JournalRecordEntries) CmdTextHeaderLength() uint64 {
	return 4
}

func (m *JournalRecordEntries) CmdTextLength() uint32 {
	return Uint32LittleEndian(m.buffer[m.SbePosition():])
}

func (m *JournalRecordEntries) SkipCmdText() uint64 {
	lengthOfLengthField := uint64(4)
	lengthPosition := m.SbePosition()
	dataLength := uint64(Uint32LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
	m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
	return dataLength
}

func (m *JournalRecordEntries) CmdText() string {
	lengthFieldValue := uint64(Uint32LittleEndian(m.buffer[m.SbePosition() : m.SbePosition()+4]))
	m.SetSbePosition(m.SbePosition() + uint64(4))
	pos := m.SbePosition()
	m.SetSbePosition(pos + lengthFieldValue)
	return string(m.buffer[pos : pos+lengthFieldValue])
}

func (m *JournalRecordEntries) GetCmdText(dst []byte) int {
	lengthOfLengthField := uint64(4)
	lengthPosition := m.SbePosition()
	m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
	dataLength := uint64(Uint32LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
	bytesToCopy := dataLength
	if uint64(len(dst)) < dataLength {
		bytesToCopy = uint64(len(dst))
	}
	pos := m.SbePosition()
	m.SetSbePosition(pos + dataLength)
	copy(dst, m.buffer[pos:pos+bytesToCopy])
	return int(bytesToCopy)
}

func (m *JournalRecordEntries) PutCmdTextLen(src string, length uint32) *JournalRecordEntries {
	lengthOfLengthField := uint64(4)
	lengthPosition := m.SbePosition()
	m.SetSbePosition(lengthPosition + lengthOfLengthField)
	PutUint32LittleEndian(m.buffer[lengthPosition:], length)
	if length != uint32(0) {
		pos := m.SbePosition()
		m.SetSbePosition(pos + uint64(length))
		copy(m.buffer[pos:], src)
	}
	return m
}

func (m *JournalRecordEntries) GetCmdTextAsString() string {
	lengthOfLengthField := uint64(4)
	lengthPosition := m.SbePosition()
	dataLength := uint64(Uint32LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
	m.SetSbePosition(lengthPosition + lengthOfLengthField)
	pos := m.SbePosition()
	m.SetSbePosition(pos + dataLength)
	return string(m.buffer[pos : pos+dataLength])
}

func (m *JournalRecordEntries) GetCmdTextAsJsonEscapedString() string {
	oss := strings.Builder{}
	s := m.GetCmdTextAsString()

	for _, c := range s {
		switch c {
		case '"':
			oss.WriteString("\\\"")
		case '\\':
			oss.WriteString("\\\\")
		case '\b':
			oss.WriteString("\\b")
		case '\f':
			oss.WriteString("\\f")
		case '\n':
			oss.WriteString("\\n")
		case '\r':
			oss.WriteString("\\r")
		case '\t':
			oss.WriteString("\\t")

		default:
			if '\x00' <= c && c <= '\x1f' {
				fmt.Fprintf(&oss, "%x", c)
			} else {
				oss.WriteString(string(c))
			}
		}
	}

	return oss.String()
}

func (m *JournalRecordEntries) PutCmdText(str string) *JournalRecordEntries {
	if len(str) > 1073741824 {
		panic("string too long for length type [E109]")
	}
	return m.PutCmdTextLen(str, uint32(len(str)))
}

func (writer *JournalRecordEntries) String() string {
	builder := strings.Builder{}
	builder.WriteString("{")
	builder.WriteString(`"entryTermId": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.EntryTermId()))

	builder.WriteString(", ")
	builder.WriteString(`"entryIndex": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.EntryIndex()))

	builder.WriteString(", ")
	builder.WriteString(`"entryTimestamp": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.EntryTimestamp()))

	builder.WriteString(", ")
	builder.WriteString(`"commandKey": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.CommandKey()))

	builder.WriteString(", ")
	builder.WriteString(`"cmdQty": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.CmdQty()))

	builder.WriteString(", ")
	builder.WriteString(`"cmdPrice": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.CmdPrice()))

	builder.WriteString(", ")
	builder.WriteString(`"cmdFlag": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.CmdFlag()))

	builder.WriteString(", ")
	builder.WriteString(`"cmdText": `)
	builder.WriteString(`"`)
	writer.SkipCmdText()
	builder.WriteString(" bytes of raw data")
	builder.WriteString("}")

	return builder.String()
}

func (m *JournalRecordEntries) Skip() {
	m.SkipCmdText()
}

func (m *JournalRecordEntries) IsConstLength() bool {
	return false
}

func (m *JournalRecordEntries) ComputeLength(CmdTextLength int) (int, error) {
	length := uint64(m.SbeBlockLength())

	length += m.CmdTextHeaderLength()
	if m.CmdTextLength() > 1073741824 {
		return 0, fmt.Errorf("CmdTextLength too long for length type [E109]")
	}
	length += uint64(m.CmdTextLength())

	return int(length), nil
}
func (m *JournalRecord) EntriesId() int {
	return 10
}

func (m *JournalRecord) Entries() *JournalRecordEntries {
	m._Entries.WrapForDecode(m.buffer, m.sbePositionPtr(), m.actingVersion, m.bufferLength)
	return &m._Entries
}

func (m *JournalRecord) EntriesCount(count uint16) *JournalRecordEntries {
	m._Entries.WrapForEncode(m.buffer, count, m.sbePositionPtr(), m.actingVersion, m.bufferLength)
	return &m._Entries
}

func (m *JournalRecord) EntriesSinceVersion() uint64 {
	return 0
}

func (m *JournalRecord) EntriesInActingVersion() bool {
	return true
}

func (writer *JournalRecord) String() string {
	var builder strings.Builder
	builder.WriteString("{\"Name\": \"JournalRecord\", ")
	builder.WriteString(fmt.Sprintf("\"sbeTemplateId\": %d", writer.SbeTemplateId()))
	builder.WriteString(", ")

	builder.WriteString(`"leadershipTermId": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.LeadershipTermId()))

	builder.WriteString(", ")
	builder.WriteString(`"logPosition": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.LogPosition()))

	builder.WriteString(", ")
	builder.WriteString(`"timestamp": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Timestamp()))

	builder.WriteString(", ")
	builder.WriteString(`"clusterSessionId": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.ClusterSessionId()))

	builder.WriteString(", ")
	builder.WriteString(`"correlationId": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.CorrelationId()))

	builder.WriteString(", ")
	builder.WriteString(`"leaderMemberId": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.LeaderMemberId()))

	builder.WriteString(", ")
	builder.WriteString(`"serviceId": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.ServiceId()))

	builder.WriteString(", ")
	builder.WriteString(`"eventType": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.EventType()))

	builder.WriteString(", ")
	builder.WriteString(`"flags": `)
	builder.WriteString(fmt.Sprintf(`"%v"`, writer.Flags()))

	builder.WriteString(", ")
	{
		atLeastOne := false
		builder.WriteString(`"entries": [`)
		writer.Entries().ForEach(
			func(value *JournalRecordEntries) {
				if atLeastOne {
					builder.WriteString(", ")
				}
				atLeastOne = true
				builder.WriteString(value.String())
			})
		builder.WriteString("]")
	}

	builder.WriteString("}")

	return builder.String()
}

func (m *JournalRecord) Skip() {
	for EntriesGroup := m.Entries(); EntriesGroup.HasNext(); {
		EntriesGroup.Next().Skip()
	}
}

func (m *JournalRecord) IsConstLength() bool {
	return false
}

func (m *JournalRecord) ComputeLength(EntriesItemLengths []struct{ CmdTextLength int }) (int, error) {
	length := uint64(m.SbeBlockLength())

	length += m.Entries().SbeHeaderSize()
	if len(EntriesItemLengths) > 65534 {
		panic("len(EntriesItemLengths) outside of allowed range [E110]")
	}

	for _, e := range EntriesItemLengths {
		l, err := m.Entries().ComputeLength(e.CmdTextLength)
		if err != nil {
			return 0, err
		}
		length += uint64(l)
	}

	return int(length), nil
}
